"""
features/tv_indicators/ - Dynamic TV indicator registry.
Each sub-module exposes add_{name}_features(df, config) -> df.
Modules are auto-generated by tv_research_loop and imported dynamically.
"""
import importlib
from typing import Dict, Any

import pandas as pd


def apply_tv_indicators(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """Load and apply all enabled TV indicator modules.

    Reads config["tv_indicators"] and for each enabled entry imports
    trade2.features.tv_indicators.{name} and calls add_{name}_features(df, config).
    Failures are caught and printed as warnings so the pipeline continues.
    """
    tv_cfg = (config or {}).get("tv_indicators", {})
    for name, ind_cfg in tv_cfg.items():
        if isinstance(ind_cfg, dict) and ind_cfg.get("enabled", False):
            try:
                mod = importlib.import_module(f"trade2.features.tv_indicators.{name}")
                add_fn = getattr(mod, f"add_{name}_features")
                df = add_fn(df, config)
            except Exception as e:
                print(f"  [tv] WARN: {name} failed: {e}")
    return df
