"""
features/tv_indicators/adaptive_momentum_divergence.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T14:58:27
"""
import numpy as np
import pandas as pd
import talib

def add_adaptive_momentum_divergence_features(df, config):
    df = df.copy()
    fast_period = config.get('fast_period', 5)
    slow_period = config.get('slow_period', 10)
    smooth_period = config.get('smooth_period', 3)
    
    close = df['Close']
    
    fast_roc = talib.ROC(close.values, timeperiod=fast_period)
    slow_roc = talib.ROC(close.values, timeperiod=slow_period)
    osc = fast_roc - slow_roc
    smoothed_osc = pd.Series(talib.EMA(osc, timeperiod=smooth_period), index=df.index)
    
    crossover_bull = (smoothed_osc > 0) & (smoothed_osc.shift(1) <= 0)
    crossover_bear = (smoothed_osc < 0) & (smoothed_osc.shift(1) >= 0)
    
    window = 5
    min_close = close.rolling(window=window, min_periods=1).min()
    min_osc = smoothed_osc.rolling(window=window, min_periods=1).min()
    max_close = close.rolling(window=window, min_periods=1).max()
    max_osc = smoothed_osc.rolling(window=window, min_periods=1).max()
    
    bullish_div = (close == min_close) & (smoothed_osc != min_osc)
    bearish_div = (close == max_close) & (smoothed_osc != max_osc)
    
    df['adaptive_momentum_divergence_bull'] = (crossover_bull | bullish_div).shift(1).fillna(False)
    df['adaptive_momentum_divergence_bear'] = (crossover_bear | bearish_div).shift(1).fillna(False)
    
    return df