"""
features/tv_indicators/aroon.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-17T16:54:43
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_aroon_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Aroon trend indicator features.
    
    Aroon measures trend direction and strength:
    - Aroon Up: Percentage of time since highest high in period
    - Aroon Down: Percentage of time since lowest low in period
    
    Bullish: Aroon Up > Aroon Down (uptrend)
    Bearish: Aroon Down > Aroon Up (downtrend)
    
    All outputs shift(1) for lag safety.
    """
    # Get parameters
    aroon_cfg = config.get('tv_indicators', {}).get('aroon', {})
    period = aroon_cfg.get('period', 25)
    
    out = df.copy()
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    
    # Calculate Aroon indicator using TA-Lib
    # TA-LIB returns: aroon_down, aroon_up (note order)
    aroon_down, aroon_up = talib.AROON(high, low, timeperiod=period)
    
    # Determine bullish/bearish conditions
    bull_raw = aroon_up > aroon_down
    bear_raw = aroon_down > aroon_up
    
    # Helper: numpy-level 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty_like(arr)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr
    
    idx = out.index
    out["aroon_up"] = pd.Series(aroon_up, index=idx).shift(1)
    out["aroon_down"] = pd.Series(aroon_down, index=idx).shift(1)
    out["aroon_bull"] = pd.Series(_lag1(bull_raw), index=idx, dtype=bool)
    out["aroon_bear"] = pd.Series(_lag1(bear_raw), index=idx, dtype=bool)
    
    return out