"""
features/tv_indicators/aroon_indicator.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T21:41:26
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_aroon_indicator_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Aroon indicator for scalping (short periods).
    
    Aroon Up = ((period - periods since highest high) / period) * 100
    Aroon Down = ((period - periods since lowest low) / period) * 100
    
    Bullish when: Aroon Up > Aroon Down AND Aroon Up > 50
    Bearish when: Aroon Down > Aroon Up AND Aroon Down > 50
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["aroon_indicator"]
    
    Returns:
        df copy with Aroon columns added, all shifted by 1 bar.
    """
    # Get parameters with scalping constraints
    params = config.get('tv_indicators', {}).get('aroon_indicator', {})
    period = min(max(params.get('period', 8), 3), 14)  # Constrain to 3-14 for scalping
    
    out = df.copy()
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    
    # Calculate Aroon using TA-Lib
    aroon_up, aroon_down = talib.AROON(high, low, timeperiod=period)
    
    # Define bullish/bearish conditions
    bull_condition = (aroon_up > aroon_down) & (aroon_up > 50)
    bear_condition = (aroon_down > aroon_up) & (aroon_down > 50)
    
    # Create boolean columns and shift by 1 for lag safety
    out['aroon_indicator_bull'] = pd.Series(bull_condition, index=out.index).shift(1)
    out['aroon_indicator_bear'] = pd.Series(bear_condition, index=out.index).shift(1)
    
    return out