"""
features/tv_indicators/awesome_oscillator.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-19T01:18:09
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_awesome_oscillator_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Awesome Oscillator momentum features.

    AO = SMA(median_price, fast) - SMA(median_price, slow)
    where median_price = (High + Low) / 2

    Bullish conditions (both required):
      1. AO > 0
      2. Current AO > previous AO (momentum rising)

    Bearish conditions (both required):
      1. AO < 0
      2. Current AO < previous AO (momentum falling)

    Args:
        df:     OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["awesome_oscillator"].

    Returns:
        df copy with Awesome Oscillator columns added.
    """
    cfg = config.get("tv_indicators", {}).get("awesome_oscillator", {})
    fast_period = cfg.get("fast_period", 5)
    slow_period = cfg.get("slow_period", 34)
    
    # Create a copy to avoid modifying the original
    df = df.copy()
    
    # Standardize column names to lowercase
    df.columns = df.columns.str.lower()
    
    # Calculate median price
    median_price = (df['high'] + df['low']) / 2
    
    # Calculate Awesome Oscillator
    fast_sma = talib.SMA(median_price, timeperiod=fast_period)
    slow_sma = talib.SMA(median_price, timeperiod=slow_period)
    awesome_oscillator = fast_sma - slow_sma
    
    # Calculate conditions
    ao_positive = awesome_oscillator > 0
    ao_increasing = awesome_oscillator > awesome_oscillator.shift(1)
    ao_negative = awesome_oscillator < 0
    ao_decreasing = awesome_oscillator < awesome_oscillator.shift(1)
    
    # Create boolean signals
    bull_signal = ao_positive & ao_increasing
    bear_signal = ao_negative & ao_decreasing
    
    # Add features with shift for lag safety
    df['awesome_oscillator_value'] = awesome_oscillator.shift(1)
    df['awesome_oscillator_bull'] = bull_signal.shift(1).astype(bool)
    df['awesome_oscillator_bear'] = bear_signal.shift(1).astype(bool)
    
    return df