"""
features/tv_indicators/bollinger_bands_percent_b.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T20:23:29
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_bollinger_bands_percent_b_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Bollinger Bands %B oscillator features for 5M scalping.
    
    Logic:
      1. Calculate BB %B = (Close - LowerBand) / (UpperBand - LowerBand)
      2. Oversold threshold = 0.2 (fast mean-reversion bounce zone)
      3. Overbought threshold = 0.8 (fast mean-reversion reversal zone)
      4. Bull signal: %B crosses above 0.2 from below (oversold bounce)
      5. Bear signal: %B crosses below 0.8 from above (overbought rejection)
      
    All signals shift(1) for safe next-bar execution.
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["bollinger_bands_percent_b"]
    
    Returns:
        df copy with BB %B columns added.
    """
    tv_indicators = config.get('tv_indicators', {})
    bb_config = tv_indicators.get('bollinger_bands_percent_b', {})
    
    # Scalping periods (3-14 bars max)
    period = min(max(bb_config.get('period', 14), 3), 14)
    stddev = bb_config.get('stddev', 2.0)
    
    out = df.copy()
    close = out['Close'].astype(float).values
    
    # Calculate Bollinger Bands
    upper, middle, lower = talib.BBANDS(
        close, 
        timeperiod=period,
        nbdevup=stddev,
        nbdevdn=stddev
    )
    
    # Calculate %B
    percent_b = (close - lower) / (upper - lower)
    
    # Create signals
    oversold_threshold = 0.2
    overbought_threshold = 0.8
    
    # Bull signal: crosses above oversold threshold
    cross_above_oversold = (percent_b > oversold_threshold) & (np.roll(percent_b, 1) <= oversold_threshold)
    
    # Bear signal: crosses below overbought threshold
    cross_below_overbought = (percent_b < overbought_threshold) & (np.roll(percent_b, 1) >= overbought_threshold)
    
    # Shift all outputs by 1 to avoid lookahead bias
    out['bollinger_bands_percent_b_value'] = np.roll(percent_b, 1)
    out['bollinger_bands_percent_b_bull'] = np.roll(cross_above_oversold, 1).astype(bool)
    out['bollinger_bands_percent_b_bear'] = np.roll(cross_below_overbought, 1).astype(bool)
    
    return out