"""
features/tv_indicators/bollinger_band_mean_reversion.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-24T16:59:12
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_bollinger_band_mean_reversion_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    params = config.get('tv_indicators', {}).get('bollinger_band_mean_reversion', {})
    period = int(params.get('period', 10))
    std_dev = float(params.get('std_dev', 2.0))

    # Clamp to scalping-safe range
    period = max(3, min(period, 14))

    out = df.copy()
    close = out['Close'].astype(float).values
    high  = out['High'].astype(float).values
    low   = out['Low'].astype(float).values

    # Bollinger Bands via talib
    upper, middle, lower = talib.BBANDS(close, timeperiod=period, nbdevup=std_dev, nbdevdn=std_dev, matype=0)

    # Previous bar values (numpy shift)
    def _lag1(arr: np.ndarray) -> np.ndarray:
        result = np.empty_like(arr)
        result[0] = np.nan
        result[1:] = arr[:-1]
        return result

    def _lag1_bool(arr: np.ndarray) -> np.ndarray:
        result = np.zeros(len(arr), dtype=bool)
        result[1:] = arr[:-1]
        return result

    prev_close = _lag1(close)
    prev_low   = _lag1(low)
    prev_high  = _lag1(high)
    prev_lower = _lag1(lower)
    prev_upper = _lag1(upper)

    # Bull signal:
    #   Previous bar: low touched or pierced lower band (prev_low <= prev_lower)
    #   Current bar:  close is back above lower band (close > lower)
    #   i.e. mean reversion bounce from lower band
    bull_raw = (
        (~np.isnan(lower)) &
        (~np.isnan(prev_lower)) &
        (prev_low <= prev_lower) &
        (close > lower)
    )

    # Bear signal:
    #   Previous bar: high touched or pierced upper band (prev_high >= prev_upper)
    #   Current bar:  close is back below upper band (close < upper)
    #   i.e. mean reversion drop from upper band
    bear_raw = (
        (~np.isnan(upper)) &
        (~np.isnan(prev_upper)) &
        (prev_high >= prev_upper) &
        (close < upper)
    )

    idx = out.index

    # Shift(1) all outputs for lag safety
    out['bollinger_band_mean_reversion_upper']  = pd.Series(upper,  index=idx).shift(1)
    out['bollinger_band_mean_reversion_middle'] = pd.Series(middle, index=idx).shift(1)
    out['bollinger_band_mean_reversion_lower']  = pd.Series(lower,  index=idx).shift(1)
    out['bollinger_band_mean_reversion_bull']   = pd.Series(_lag1_bool(bull_raw), index=idx, dtype=bool)
    out['bollinger_band_mean_reversion_bear']   = pd.Series(_lag1_bool(bear_raw), index=idx, dtype=bool)

    return out