"""
features/tv_indicators/buy_sell_climax_rotation.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-24T17:53:48
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_buy_sell_climax_rotation_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Buy/Sell Climax Rotation indicator.

    A one-sided climax (extremely high volume with a strong directional move)
    followed by an opposite directional close suggests a rotational scalp setup.

    Climax Detection:
      - Volume spike: volume > climax_mult * rolling_mean(volume, vol_period)
      - Buy climax:  volume spike AND close < open (bearish close on high-vol up move)
                     i.e. price tried to push up but closed down = exhaustion top
      - Sell climax: volume spike AND close > open (bullish close on high-vol down move)
                     i.e. price tried to push down but closed up = exhaustion bottom

    Rotation Signal:
      - Bull rotation: sell climax on previous bar AND current close > previous close
      - Bear rotation: buy climax on previous bar AND current close < previous close

    All outputs shift(1) for lag safety.

    Args:
        df:     OHLCV DataFrame with Open, High, Low, Close, Volume columns
        config: Full config dict

    Returns:
        df copy with buy_sell_climax_rotation_ columns added.
    """
    params = config.get('tv_indicators', {}).get('buy_sell_climax_rotation', {})
    climax_mult = float(params.get('climax_mult', 1.7))
    vol_period  = int(params.get('vol_period', 8))

    out    = df.copy()
    close  = out['Close'].astype(float).values
    open_  = out['Open'].astype(float).values
    high   = out['High'].astype(float).values
    low    = out['Low'].astype(float).values
    volume = out['Volume'].astype(float).values
    n      = len(close)

    # --- Volume spike detection ---
    # Rolling mean of volume over vol_period using talib SMA
    vol_ma = talib.SMA(volume, timeperiod=vol_period)
    vol_spike = volume > (climax_mult * vol_ma)

    # --- Candle body direction ---
    bullish_bar = close > open_   # close above open
    bearish_bar = close < open_   # close below open

    # --- Bar range and body size for climax quality ---
    bar_range = high - low
    body_size = np.abs(close - open_)

    # Body must be meaningful (at least 25% of bar range) to count as directional
    significant_body = body_size >= (0.25 * bar_range)

    # --- Buy climax: high volume + bearish close (exhaustion top) ---
    # Strong up volume but price rejected and closed below open
    buy_climax = vol_spike & bearish_bar & significant_body

    # --- Sell climax: high volume + bullish close (exhaustion bottom) ---
    # Strong down volume but price absorbed and closed above open
    sell_climax = vol_spike & bullish_bar & significant_body

    # --- Rotation signals (require climax on prior bar + confirming follow-through) ---
    # We use numpy shift (1-bar lag) to check previous bar's climax

    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.zeros(len(arr), dtype=bool)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr

    prev_buy_climax  = _lag1(buy_climax)
    prev_sell_climax = _lag1(sell_climax)
    prev_close       = np.empty(n, dtype=float)
    prev_close[0]    = np.nan
    prev_close[1:]   = close[:-1]

    # Bull rotation: previous bar was a sell climax AND current bar closes higher
    bull_rotation_raw = prev_sell_climax & (close > prev_close)

    # Bear rotation: previous bar was a buy climax AND current bar closes lower
    bear_rotation_raw = prev_buy_climax & (close < prev_close)

    # --- Additional confluence: short-term momentum via EMA crossover ---
    # Fast EMA (3) vs Slow EMA (8) for trend filter
    ema_fast = talib.EMA(close, timeperiod=3)
    ema_slow = talib.EMA(close, timeperiod=8)
    momentum_bull = ema_fast > ema_slow
    momentum_bear = ema_fast < ema_slow

    # Combine rotation signal with momentum confirmation
    bull_signal_raw = bull_rotation_raw & momentum_bull
    bear_signal_raw = bear_rotation_raw & momentum_bear

    # --- RSI filter for additional overbought/oversold context ---
    rsi = talib.RSI(close, timeperiod=7)
    rsi_oversold  = rsi < 40.0   # support bull rotation
    rsi_overbought = rsi > 60.0  # support bear rotation

    # Final signals: rotation + momentum + rsi context
    # (RSI is optional confluence — use OR to not over-filter in scalping)
    bull_final_raw = bull_rotation_raw & (momentum_bull | rsi_oversold)
    bear_final_raw = bear_rotation_raw & (momentum_bear | rsi_overbought)

    # --- Shift(1) for lag safety ---
    idx = out.index

    out['buy_sell_climax_rotation_vol_ma']        = pd.Series(vol_ma,       index=idx).shift(1)
    out['buy_sell_climax_rotation_vol_spike']      = pd.Series(vol_spike,    index=idx, dtype=bool).shift(1)
    out['buy_sell_climax_rotation_buy_climax']     = pd.Series(buy_climax,   index=idx, dtype=bool).shift(1)
    out['buy_sell_climax_rotation_sell_climax']    = pd.Series(sell_climax,  index=idx, dtype=bool).shift(1)
    out['buy_sell_climax_rotation_ema_fast']       = pd.Series(ema_fast,     index=idx).shift(1)
    out['buy_sell_climax_rotation_ema_slow']       = pd.Series(ema_slow,     index=idx).shift(1)
    out['buy_sell_climax_rotation_rsi']            = pd.Series(rsi,          index=idx).shift(1)
    out['buy_sell_climax_rotation_bull']           = pd.Series(bull_final_raw, index=idx, dtype=bool).shift(1)
    out['buy_sell_climax_rotation_bear']           = pd.Series(bear_final_raw, index=idx, dtype=bool).shift(1)

    return out