"""
features/tv_indicators/cci.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-19T00:24:00
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_cci_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute CCI (Commodity Channel Index) momentum features.
    
    CCI measures deviation of typical price from its statistical mean.
    Common interpretation:
      - cci_bull: CCI > 0 (positive momentum/trend)
      - cci_bear: CCI < 0 (negative momentum/trend)
    
    All outputs shift(1) for lag safety.
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["cci"].
    
    Returns:
        df copy with CCI columns added.
    """
    cci_cfg = config.get("tv_indicators", {}).get("cci", {})
    period = cci_cfg.get("period", 20)
    
    out = df.copy()
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    close = out["Close"].astype(float).values
    
    # Calculate CCI using TA-Lib
    cci = talib.CCI(high, low, close, timeperiod=period)
    
    # Raw signals (before shift)
    cci_bull_raw = cci > 0
    cci_bear_raw = cci < 0
    
    # Helper: numpy-level 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty_like(arr)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr
    
    # Apply shift(1) for all outputs
    idx = out.index
    out["cci"] = pd.Series(cci, index=idx).shift(1)
    out["cci_bull"] = pd.Series(_lag1(cci_bull_raw), index=idx, dtype=bool)
    out["cci_bear"] = pd.Series(_lag1(cci_bear_raw), index=idx, dtype=bool)
    
    return out