"""
features/tv_indicators/chaikin_money_flow.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T15:46:52
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_chaikin_money_flow_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Chaikin Money Flow (CMF) indicator for scalping on 5M charts.
    
    Bullish when CMF > 0 (buying pressure dominant).
    Bearish when CMF < 0 (selling pressure dominant).
    All outputs shift(1) for lag safety.
    """
    params = config.get('tv_indicators', {}).get('chaikin_money_flow', {})
    period = params.get('period', 8)
    
    # Ensure period is within scalping range
    period = min(max(3, period), 14)
    
    out = df.copy()
    high = out['High'].astype(float).values
    low = out['Low'].astype(float).values
    close = out['Close'].astype(float).values
    volume = out['Volume'].astype(float).values
    
    # Avoid division by zero in money flow multiplier
    high_low_range = high - low
    zero_range_mask = high_low_range == 0
    high_low_range[zero_range_mask] = 1.0  # Set to 1 to avoid NaN
    
    # Money Flow Multiplier
    mfm = ((close - low) - (high - close)) / high_low_range
    mfm = np.clip(mfm, -1.0, 1.0)
    
    # Money Flow Volume
    mfv = mfm * volume
    
    # CMF = sum(MFV) / sum(Volume) over period
    cmf = np.full_like(close, np.nan)
    for i in range(period - 1, len(close)):
        mfv_window = mfv[i - period + 1:i + 1]
        vol_window = volume[i - period + 1:i + 1]
        if np.sum(vol_window) != 0:
            cmf[i] = np.sum(mfv_window) / np.sum(vol_window)
        else:
            cmf[i] = 0.0
    
    # Bullish/Bearish conditions
    bullish = cmf > 0
    bearish = cmf < 0
    
    # Apply shift(1) for lag safety
    out['chaikin_money_flow_cmf'] = pd.Series(cmf, index=out.index).shift(1)
    out['chaikin_money_flow_bull'] = pd.Series(bullish, index=out.index).shift(1).fillna(False).astype(bool)
    out['chaikin_money_flow_bear'] = pd.Series(bearish, index=out.index).shift(1).fillna(False).astype(bool)
    
    return out