"""
features/tv_indicators/chande_momentum.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-18T23:41:47
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_chande_momentum_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Chande Momentum Oscillator features.
    
    Formula: 
        mom = close - close[1]
        su = sum of positive mom over period
        sd = sum of negative mom over period (absolute)
        cmo = 100 * (su - sd) / (su + sd)
    
    Signals:
        chande_momentum_bull: CMO > threshold_high (default 50)
        chande_momentum_bear: CMO < threshold_low (default -50)
    """
    df = df.copy()
    period = config.get('period', 14)
    threshold_high = config.get('cmo_threshold_high', 50)
    threshold_low = config.get('cmo_threshold_low', -50)
    
    # Use lowercase column name which is standard in financial data
    df['chande_momentum'] = talib.CMO(df['Close'], timeperiod=period)
    df['chande_momentum_bull'] = df['chande_momentum'] > threshold_high
    df['chande_momentum_bear'] = df['chande_momentum'] < threshold_low
    
    # Shift for lag safety
    df['chande_momentum'] = df['chande_momentum'].shift(1)
    df['chande_momentum_bull'] = df['chande_momentum_bull'].shift(1)
    df['chande_momentum_bear'] = df['chande_momentum_bear'].shift(1)
    
    return df