"""
features/tv_indicators/chande_momentum_oscillator.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T16:16:27
"""
import numpy as np
import pandas as pd
import talib

def add_chande_momentum_oscillator_features(df, config):
    df = df.copy()
    
    price_col = config.get('price_column', 'close')
    if price_col not in df.columns:
        for col in df.columns:
            if col.lower() == price_col.lower():
                price_col = col
                break
        if price_col not in df.columns:
            numeric_cols = df.select_dtypes(include=[np.number]).columns
            if len(numeric_cols) > 0:
                price_col = numeric_cols[0]
            else:
                raise ValueError("No numeric column found to compute CMO.")
    
    price_series = pd.to_numeric(df[price_col], errors='coerce')
    if price_series.isnull().all():
        raise ValueError("Price column contains only non-numeric values.")
    price_series = price_series.ffill().bfill()
    
    periods = config.get('periods', [14])
    for period in periods:
        cmo = talib.CMO(price_series.values, timeperiod=period)
        df[f'chande_momentum_oscillator_{period}'] = pd.Series(cmo, index=df.index).shift(1)
    
    last_period = periods[-1]
    df['chande_momentum_oscillator_bull'] = (df[f'chande_momentum_oscillator_{last_period}'] > 0).shift(1)
    df['chande_momentum_oscillator_bear'] = (df[f'chande_momentum_oscillator_{last_period}'] < 0).shift(1)
    
    return df