"""
features/tv_indicators/choppiness_index_oscillator.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T18:17:11
"""
import numpy as np
import pandas as pd
import talib

def add_choppiness_index_oscillator_features(df, config):
    df = df.copy()
    
    period = config.get('period', 14)
    smooth_period = config.get('smooth_period', 3)
    
    high_col = None
    low_col = None  
    close_col = None
    
    for col in df.columns:
        if col.lower() == 'high':
            high_col = col
        elif col.lower() == 'low':
            low_col = col
        elif col.lower() == 'close':
            close_col = col
    
    if high_col is None or low_col is None or close_col is None:
        raise ValueError("Required columns (high, low, close) not found in DataFrame")
    
    high = df[high_col]
    low = df[low_col]
    close = df[close_col]
    
    tr = np.maximum(
        high - low,
        np.maximum(
            abs(high - close.shift(1)),
            abs(low - close.shift(1))
        )
    )
    
    atr = tr.rolling(window=period).mean()
    
    hh = high.rolling(window=period).max()
    ll = low.rolling(window=period).min()
    
    denominator = hh - ll
    denominator = denominator.replace(0, np.nan)
    
    ci_raw = 100 * np.log10(atr / denominator) / np.log10(period)
    ci_smoothed = ci_raw.rolling(window=smooth_period).mean()
    
    df['choppiness_index_oscillator_raw'] = ci_raw.shift(1)
    df['choppiness_index_oscillator_smoothed'] = ci_smoothed.shift(1)
    
    ci_smoothed_shifted = ci_smoothed.shift(1)
    ci_raw_shifted = ci_raw.shift(1)
    
    df['choppiness_index_oscillator_bull'] = (ci_smoothed_shifted < 38.2) & (ci_raw_shifted > ci_smoothed_shifted)
    df['choppiness_index_oscillator_bear'] = (ci_smoothed_shifted > 61.8) & (ci_raw_shifted < ci_smoothed_shifted)
    
    return df