"""
features/tv_indicators/commodity_channel_index.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T17:00:27
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_commodity_channel_index_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Commodity Channel Index (CCI) features for scalping.
    
    CCI formula: (Typical Price - SMA(TP, period)) / (0.015 * Mean Deviation)
    Typical Price = (High + Low + Close) / 3
    
    Bullish: CCI crosses above -100 (oversold bounce) OR CCI > 0 (positive momentum)
    Bearish: CCI crosses below 100 (overbought reversal) OR CCI < 0 (negative momentum)
    
    All outputs shift(1) for lag safety.
    """
    out = df.copy()
    
    # Get parameters with scalping-friendly defaults
    indicator_config = config.get('tv_indicators', {}).get('commodity_channel_index', {})
    period = int(indicator_config.get('period', 10))
    
    # Ensure period is within scalping range (3-14 bars)
    period = max(3, min(period, 14))
    
    # Calculate CCI
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    close = out["Close"].astype(float).values
    
    cci = talib.CCI(high, low, close, timeperiod=period)
    
    # Calculate CCI crossing signals
    cci_series = pd.Series(cci, index=out.index)
    
    # Cross above -100 (oversold bounce)
    cross_above_neg100 = (cci_series > -100) & (cci_series.shift(1) <= -100)
    
    # Cross below 100 (overbought reversal)
    cross_below_100 = (cci_series < 100) & (cci_series.shift(1) >= 100)
    
    # Positive/negative momentum
    cci_positive = cci_series > 0
    cci_negative = cci_series < 0
    
    # Combined bullish/bearish signals
    bull_raw = cross_above_neg100 | cci_positive
    bear_raw = cross_below_100 | cci_negative
    
    # Shift all outputs by 1 for lag safety
    out["commodity_channel_index"] = cci_series.shift(1)
    out["commodity_channel_index_bull"] = bull_raw.shift(1).astype(bool)
    out["commodity_channel_index_bear"] = bear_raw.shift(1).astype(bool)
    
    return out