"""
features/tv_indicators/connors_rsi.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T22:18:42
"""
import numpy as np
import pandas as pd
import talib

def add_connors_rsi_features(df, config):
    df = df.copy()
    
    rsi_length = config.get('rsi_length', 3)
    streak_length = config.get('streak_length', 2)
    percent_rank_length = min(config.get('percent_rank_length', 14), 20)
    
    if percent_rank_length <= 1:
        percent_rank_length = 2
    
    rsi_close = talib.RSI(df['Close'].values, timeperiod=rsi_length)
    
    streak = np.zeros(len(df))
    close_vals = df['Close'].values
    for i in range(1, len(df)):
        if close_vals[i] > close_vals[i-1]:
            streak[i] = streak[i-1] + 1 if streak[i-1] >= 0 else 1
        elif close_vals[i] < close_vals[i-1]:
            streak[i] = streak[i-1] - 1 if streak[i-1] <= 0 else -1
        else:
            streak[i] = 0
    
    rsi_streak = talib.RSI(streak, timeperiod=streak_length)
    
    def calc_percentrank(series, window):
        pr = np.full(len(series), np.nan)
        for i in range(window-1, len(series)):
            window_vals = series[i-window+1:i+1]
            current_val = window_vals[-1]
            less_count = np.sum(window_vals[:-1] < current_val)
            pr[i] = (less_count / (window - 1)) * 100
        return pr
    
    pct_rank = calc_percentrank(streak, percent_rank_length)
    
    components = np.column_stack([rsi_close, rsi_streak, pct_rank])
    connors_rsi = np.nanmean(components, axis=1)
    
    df['connors_rsi'] = pd.Series(connors_rsi).shift(1)
    
    connors_rsi_series = pd.Series(connors_rsi)
    bull_cross = (connors_rsi_series > 20) & (connors_rsi_series.shift(1) <= 20)
    bear_cross = (connors_rsi_series < 80) & (connors_rsi_series.shift(1) >= 80)
    
    df['connors_rsi_bull'] = bull_cross.shift(1).astype(bool)
    df['connors_rsi_bear'] = bear_cross.shift(1).astype(bool)
    
    return df