"""
features/tv_indicators/detrended_rsi.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-19T02:22:13
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_detrended_rsi_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Detrended RSI features.
    
    The indicator centers RSI around the neutral 50 level to capture
    directional acceleration and mean reversion.
    
    Bullish when centered RSI > 0 (RSI > 50)
    Bearish when centered RSI < 0 (RSI < 50)
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["detrended_rsi"]
    
    Returns:
        df copy with detrended RSI columns added.
    """
    out = df.copy()
    close = out["Close"].astype(float).values
    
    # Get parameters
    rsi_config = config.get("tv_indicators", {}).get("detrended_rsi", {})
    period = rsi_config.get("period", 14)
    
    # Compute RSI
    rsi = talib.RSI(close, timeperiod=period)
    
    # Center around 50 (detrend)
    detrended_rsi = rsi - 50.0
    
    # Create signals
    detrended_rsi_bull_raw = detrended_rsi > 0
    detrended_rsi_bear_raw = detrended_rsi < 0
    
    # Shift(1) for lag safety
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty_like(arr, dtype=bool)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr
    
    idx = out.index
    out["detrended_rsi"] = pd.Series(detrended_rsi, index=idx).shift(1)
    out["detrended_rsi_bull"] = pd.Series(_lag1(detrended_rsi_bull_raw), index=idx, dtype=bool)
    out["detrended_rsi_bear"] = pd.Series(_lag1(detrended_rsi_bear_raw), index=idx, dtype=bool)
    
    return out