"""
features/tv_indicators/donchian_width.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-17T16:23:30
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_donchian_width_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Donchian channel width normalized by mid-price.
    Measures trend strength and breakout potential.
    
    All outputs shift(1) for lag safety.
    """
    # Get parameters from config
    cfg = config.get('tv_indicators', {}).get('donchian_width', {})
    period = cfg.get('period', 20)
    
    out = df.copy()
    high = out['High'].astype(float).values
    low = out['Low'].astype(float).values
    
    # Calculate Donchian channels
    highest_high = talib.MAX(high, timeperiod=period)
    lowest_low = talib.MIN(low, timeperiod=period)
    
    # Calculate width and mid-price
    width = highest_high - lowest_low
    mid_price = (highest_high + lowest_low) / 2.0
    
    # Normalize width by mid-price (percentage)
    normalized_width = (width / mid_price) * 100.0
    
    # Shift all outputs by 1 for lag safety
    idx = out.index
    out['donchian_width_highest_high'] = pd.Series(highest_high, index=idx).shift(1)
    out['donchian_width_lowest_low'] = pd.Series(lowest_low, index=idx).shift(1)
    out['donchian_width_mid'] = pd.Series(mid_price, index=idx).shift(1)
    out['donchian_width_width'] = pd.Series(width, index=idx).shift(1)
    out['donchian_width_normalized'] = pd.Series(normalized_width, index=idx).shift(1)
    
    return out