"""
features/tv_indicators/double_smoothed_rsi.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T13:50:30
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_double_smoothed_rsi_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Double Smoothed RSI for 5M scalping.
    
    Logic:
    1. Calculate RSI(close, period=rsi_period)
    2. First smoothing: EMA(RSI, period=ema1_period)
    3. Second smoothing: EMA(EMA1, period=ema2_period)
    4. Signals:
       - Bullish: Double smoothed RSI crosses above oversold (30) from below
       - Bearish: Double smoothed RSI crosses below overbought (70) from above
    
    All outputs shift(1) for lag safety.
    """
    params = config.get('tv_indicators', {}).get('double_smoothed_rsi', {})
    rsi_period = params.get('rsi_period', 10)
    ema1_period = params.get('ema1_period', 3)
    ema2_period = params.get('ema2_period', 3)
    overbought = params.get('overbought', 70.0)
    oversold = params.get('oversold', 30.0)
    
    out = df.copy()
    close = out['Close'].astype(float).values
    
    # 1. Calculate RSI
    rsi = talib.RSI(close, timeperiod=rsi_period)
    
    # 2. First smoothing
    ema1 = talib.EMA(rsi, timeperiod=ema1_period)
    
    # 3. Second smoothing
    ema2 = talib.EMA(ema1, timeperiod=ema2_period)
    
    # 4. Generate signals (raw, before shift)
    # Previous bar values for cross detection
    ema2_prev = np.roll(ema2, 1)
    ema2_prev[0] = np.nan
    
    # Bullish: crosses above oversold (from below)
    bull_cross = (ema2 > oversold) & (ema2_prev <= oversold)
    
    # Bearish: crosses below overbought (from above)
    bear_cross = (ema2 < overbought) & (ema2_prev >= overbought)
    
    # Apply shift(1) for lag safety
    out['double_smoothed_rsi_value'] = pd.Series(ema2, index=out.index).shift(1)
    out['double_smoothed_rsi_bull'] = pd.Series(bull_cross, index=out.index).shift(1).fillna(False).astype(bool)
    out['double_smoothed_rsi_bear'] = pd.Series(bear_cross, index=out.index).shift(1).fillna(False).astype(bool)
    
    return out