"""
features/tv_indicators/ease_of_movement.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T19:09:28
"""
import numpy as np
import pandas as pd
import talib

def add_ease_of_movement_features(df, config):
    df_copy = df.copy()
    
    ma_period = config.get('ma_period', 14)
    signal_period = config.get('signal_period', 9)
    
    high_col = [col for col in df_copy.columns if col.lower() == 'high'][0]
    low_col = [col for col in df_copy.columns if col.lower() == 'low'][0]
    volume_col = [col for col in df_copy.columns if col.lower() == 'volume'][0]
    
    high = df_copy[high_col].values
    low = df_copy[low_col].values
    volume = df_copy[volume_col].values
    
    distance = ((high + low) / 2) - np.roll((high + low) / 2, 1)
    distance[0] = np.nan
    
    box_ratio = volume / 100000000 / (high - low + 1e-12)
    
    eom = distance / box_ratio
    eom_ma = talib.SMA(eom, timeperiod=ma_period)
    eom_signal = talib.SMA(eom_ma, timeperiod=signal_period)
    
    df_copy['ease_of_movement_value'] = pd.Series(eom).shift(1)
    df_copy['ease_of_movement_ma'] = pd.Series(eom_ma).shift(1)
    df_copy['ease_of_movement_signal'] = pd.Series(eom_signal).shift(1)
    
    df_copy['ease_of_movement_bull'] = pd.Series((eom_ma > eom_signal)).shift(1).fillna(False).astype(bool)
    df_copy['ease_of_movement_bear'] = pd.Series((eom_ma < eom_signal)).shift(1).fillna(False).astype(bool)
    
    return df_copy