"""
features/tv_indicators/ehlers_impulse_response_oscillator.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T20:49:08
"""
import numpy as np
import pandas as pd
import talib

def add_ehlers_impulse_response_oscillator_features(df, config):
    df = df.copy()
    period = config.get('tv_indicators', {}).get('ehlers_impulse_response_oscillator', {}).get('period', 10)
    threshold = config.get('tv_indicators', {}).get('ehlers_impulse_response_oscillator', {}).get('threshold', 0.5)
    
    if period < 3:
        period = 3
    if period > 14:
        period = 14
        
    src = df['Close'].values.astype(float)
    
    beta = np.cos(2 * np.pi / period)
    gamma = 1 / np.cos(4 * np.pi * 0.5 / period)
    alpha = gamma - np.sqrt(gamma * gamma - 1)
    
    bp = np.zeros(len(src))
    for i in range(2, len(src)):
        bp[i] = 0.5 * (1 - alpha) * (src[i] - src[i-2]) + beta * (1 + alpha) * bp[i-1] - alpha * bp[i-2]
    
    iro = np.zeros(len(src))
    iro[1:] = bp[1:] - bp[:-1]
    
    df['ehlers_impulse_response_oscillator_iro'] = iro
    df['ehlers_impulse_response_oscillator_bull'] = (iro > threshold).astype(int)
    df['ehlers_impulse_response_oscillator_bear'] = (iro < -threshold).astype(int)
    
    shift_cols = ['ehlers_impulse_response_oscillator_iro', 
                  'ehlers_impulse_response_oscillator_bull', 
                  'ehlers_impulse_response_oscillator_bear']
    df[shift_cols] = df[shift_cols].shift(1)
    
    return df