"""
features/tv_indicators/ehlers_filter.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-17T17:25:08
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_ehlers_filter_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Ehlers Two-Pole Super Smoother Filter features.
    
    This is a low-lag trend following filter with minimal phase delay.
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config['tv_indicators']['ehlers_filter'].
        
    Returns:
        df copy with Ehlers Filter columns added.
    """
    out = df.copy()
    params = config.get('tv_indicators', {}).get('ehlers_filter', {})
    period = params.get('period', 20)
    
    high = out['High'].astype(float).values
    low = out['Low'].astype(float).values
    
    # Source: hl2 (high+low)/2 as used in TradingView version
    src = (high + low) / 2.0
    
    # Ehlers Two-Pole Super Smoother Filter coefficients
    a1 = np.exp(-np.sqrt(2) * np.pi / period)
    b1 = 2 * a1 * np.cos(np.sqrt(2) * np.pi / period)
    c2 = b1
    c3 = -a1 * a1
    c1 = 1 - c2 - c3
    
    # Initialize filter array
    filt = np.zeros_like(src)
    
    # First two values use source directly (no filtering possible)
    if len(src) > 0:
        filt[0] = src[0]
    if len(src) > 1:
        filt[1] = src[1]
    
    # Apply filter from index 2 onward
    for i in range(2, len(src)):
        filt[i] = c1 * (src[i] + src[i-1]) / 2 + c2 * filt[i-1] + c3 * filt[i-2]
    
    # Bullish/Bearish signals (rising/falling filter)
    bull_raw = filt > np.roll(filt, 1)
    bear_raw = filt < np.roll(filt, 1)
    
    # Handle first element (no previous value)
    if len(bull_raw) > 0:
        bull_raw[0] = False
        bear_raw[0] = False
    
    # Apply shift(1) for lag safety
    out['ehlers_filter_filt'] = pd.Series(filt, index=out.index).shift(1)
    out['ehlers_filter_bull'] = pd.Series(bull_raw, index=out.index).shift(1).fillna(False)
    out['ehlers_filter_bear'] = pd.Series(bear_raw, index=out.index).shift(1).fillna(False)
    
    return out