"""
features/tv_indicators/ehlers_adaptive_center_of_gravity.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T23:09:20
"""
import numpy as np
import pandas as pd
import talib

def add_ehlers_adaptive_center_of_gravity_features(df, config):
    df = df.copy()
    
    price_column = config.get('price_column', 'close')
    
    if price_column not in df.columns:
        price = np.full(len(df), np.nan)
    else:
        price = df[price_column].values.astype(float)
    
    cg = np.zeros(len(df))
    default_period = config.get('period', 10)
    
    for i in range(len(df)):
        current_period = min(default_period, i + 1)
        window = price[max(0, i - current_period + 1):i + 1]
        
        numerator = 0.0
        denominator = 0.0
        
        for j in range(len(window)):
            weight = len(window) - j
            numerator += weight * window[j]
            denominator += window[j]
        
        if denominator != 0:
            cg[i] = numerator / denominator
        else:
            cg[i] = 0
    
    df['ehlers_adaptive_center_of_gravity_cg'] = cg
    df['ehlers_adaptive_center_of_gravity_signal'] = talib.EMA(cg, timeperiod=default_period)
    
    df['ehlers_adaptive_center_of_gravity_bull'] = df['ehlers_adaptive_center_of_gravity_cg'] > df['ehlers_adaptive_center_of_gravity_signal']
    df['ehlers_adaptive_center_of_gravity_bear'] = df['ehlers_adaptive_center_of_gravity_cg'] < df['ehlers_adaptive_center_of_gravity_signal']
    
    df['ehlers_adaptive_center_of_gravity_cg'] = df['ehlers_adaptive_center_of_gravity_cg'].shift(1)
    df['ehlers_adaptive_center_of_gravity_signal'] = df['ehlers_adaptive_center_of_gravity_signal'].shift(1)
    df['ehlers_adaptive_center_of_gravity_bull'] = df['ehlers_adaptive_center_of_gravity_bull'].shift(1)
    df['ehlers_adaptive_center_of_gravity_bear'] = df['ehlers_adaptive_center_of_gravity_bear'].shift(1)
    
    return df