"""
features/tv_indicators/elder_ray.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-17T17:07:20
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_elder_ray_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Elder Ray bull/bear power features.
    
    Bull Power = High - EMA(Close, period)
    Bear Power = Low - EMA(Close, period)
    
    Signals:
      elder_ray_bull: True when Bull Power > 0 and Bull Power > Bear Power
      elder_ray_bear: True when Bear Power < 0 and Bear Power < Bull Power
      
    All outputs shift(1) for lag safety.
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["elder_ray"].
        
    Returns:
        df copy with elder_ray_ columns added.
    """
    indicator_cfg = config.get('tv_indicators', {}).get('elder_ray', {})
    period = indicator_cfg.get('period', 13)
    
    out = df.copy()
    close = out["Close"].astype(float).values
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    
    # EMA calculation
    ema = talib.EMA(close, timeperiod=period)
    
    # Bull and Bear Power
    bull_power = high - ema
    bear_power = low - ema
    
    # Signal conditions
    bull_condition = (bull_power > 0) & (bull_power > bear_power)
    bear_condition = (bear_power < 0) & (bear_power < bull_power)
    
    # Shift(1) for lag safety
    idx = out.index
    out["elder_ray_bull"] = pd.Series(bull_condition, index=idx).shift(1).fillna(False).astype(bool)
    out["elder_ray_bear"] = pd.Series(bear_condition, index=idx).shift(1).fillna(False).astype(bool)
    out["elder_ray_bull_power"] = pd.Series(bull_power, index=idx).shift(1)
    out["elder_ray_bear_power"] = pd.Series(bear_power, index=idx).shift(1)
    out["elder_ray_ema"] = pd.Series(ema, index=idx).shift(1)
    
    return out