"""
features/tv_indicators/er_quadrant_price_oscillator.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T21:29:52
"""
import numpy as np
import pandas as pd
import talib

def add_er_quadrant_price_oscillator_features(df, config) -> pd.DataFrame:
    df = df.copy()
    
    fast_period = config.get('fast_period', 20)
    slow_period = config.get('slow_period', 40)
    
    close_col = config.get('close_column', 'close')
    if close_col not in df.columns:
        col_lower_map = {col.lower(): col for col in df.columns}
        if close_col.lower() in col_lower_map:
            close_col = col_lower_map[close_col.lower()]
        elif 'close' in col_lower_map:
            close_col = col_lower_map['close']
        else:
            possible_cols = [col for col in df.columns if 'close' in col.lower()]
            if possible_cols:
                close_col = possible_cols[0]
            else:
                raise KeyError("No column that matches 'close' (case-insensitive) found in the DataFrame.")
    
    ema_fast = talib.EMA(df[close_col], timeperiod=fast_period)
    ema_slow = talib.EMA(df[close_col], timeperiod=slow_period)
    oscillator = ema_fast - ema_slow
    
    bull_condition = (oscillator > 0) & (df[close_col] > ema_slow)
    bear_condition = (oscillator < 0) & (df[close_col] < ema_slow)
    
    df['er_quadrant_price_oscillator_bull'] = bull_condition.shift(1)
    df['er_quadrant_price_oscillator_bear'] = bear_condition.shift(1)
    
    return df