"""
features/tv_indicators/fast_stochastic_oscillator.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T16:33:03
"""
import numpy as np
import pandas as pd
import talib

def add_fast_stochastic_oscillator_features(df, config):
    # Extract parameters with defaults
    k_period = config.get('k_period', 9)
    k_smoothing = config.get('k_smoothing', 3)
    d_smoothing = config.get('d_smoothing', 3)
    
    # Calculate lowest low and highest high
    lowest_low = talib.MIN(df['Low'].values, timeperiod=k_period)
    highest_high = talib.MAX(df['High'].values, timeperiod=k_period)
    
    # Calculate raw stochastic
    with np.errstate(divide='ignore', invalid='ignore'):
        raw_stoch = 100 * (df['Close'].values - lowest_low) / (highest_high - lowest_low)
    
    # Handle division by zero
    raw_stoch = np.nan_to_num(raw_stoch, nan=0.0, posinf=0.0, neginf=0.0)
    
    # Calculate fast %K and %D
    fast_k = talib.SMA(raw_stoch, timeperiod=k_smoothing)
    fast_d = talib.SMA(fast_k, timeperiod=d_smoothing)
    
    # Convert to pandas Series with original index
    fast_k_series = pd.Series(fast_k, index=df.index)
    fast_d_series = pd.Series(fast_d, index=df.index)
    
    # Calculate conditions for signals
    oversold = fast_k_series < 20
    overbought = fast_k_series > 80
    
    bullish_crossover = (fast_k_series > fast_d_series) & (fast_k_series.shift(1) <= fast_d_series.shift(1))
    bearish_crossover = (fast_k_series < fast_d_series) & (fast_k_series.shift(1) >= fast_d_series.shift(1))
    
    # Calculate oversold bounce and overbought reversal
    oversold_bounce = (fast_k_series.shift(1) < 20) & (fast_k_series >= 20)
    overbought_reversal = (fast_k_series.shift(1) > 80) & (fast_k_series <= 80)
    
    # Combine conditions for signals
    bull_signal = (oversold & bullish_crossover) | (oversold & oversold_bounce)
    bear_signal = (overbought & bearish_crossover) | (overbought & overbought_reversal)
    
    # Create result dataframe
    result = df.copy()
    result['fast_stochastic_oscillator_k'] = fast_k_series.shift(1)
    result['fast_stochastic_oscillator_d'] = fast_d_series.shift(1)
    result['fast_stochastic_oscillator_bull'] = bull_signal.shift(1)
    result['fast_stochastic_oscillator_bear'] = bear_signal.shift(1)
    
    return result