"""
features/tv_indicators/force_index.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T15:03:58
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_force_index_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Force Index features for scalping (short periods only).
    
    Bullish when Force Index > 0 (positive buying pressure)
    Bearish when Force Index < 0 (negative selling pressure)
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["force_index"].
    
    Returns:
        df copy with Force Index columns added.
    """
    # Get parameters with scalping-appropriate defaults
    ind_config = config.get("tv_indicators", {}).get("force_index", {})
    period = min(max(ind_config.get("period", 8), 3), 14)  # Constrain to 3-14 for scalping
    
    out = df.copy()
    close = out["Close"].astype(float).values
    volume = out["Volume"].astype(float).values
    
    # Raw Force Index: (Close - Close_prev) * Volume
    close_prev = np.roll(close, 1)
    close_prev[0] = close[0]  # Handle first element
    raw_force = (close - close_prev) * volume
    
    # EMA of raw force index
    force_index = talib.EMA(raw_force, timeperiod=period)
    
    # Create boolean columns
    out["force_index_bull"] = force_index > 0
    out["force_index_bear"] = force_index < 0
    
    # Apply lag safety shift to all new columns
    new_cols = ["force_index_bull", "force_index_bear"]
    for col in new_cols:
        out[col] = out[col].shift(1)
    
    return out