"""
features/tv_indicators/high_of_day_retake_surge.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-24T18:04:35
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_high_of_day_retake_surge_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    High of Day Retake Surge indicator for 5M scalping.

    Bull signal: Price reclaims and breaks above the rolling intraday high
                 with volume surge confirmation.
    Bear signal: Price loses and breaks below the rolling intraday low
                 with volume surge confirmation.

    All outputs shift(1) for lag safety.

    Args:
        df:     OHLCV DataFrame with columns: Open, High, Low, Close, Volume
        config: Full config dict. Reads config['tv_indicators']['high_of_day_retake_surge'].

    Returns:
        df copy with high_of_day_retake_surge_ prefixed columns added.
    """
    params = config.get('tv_indicators', {}).get('high_of_day_retake_surge', {})

    # Clamp lookback_bars to scalping range [5, 12]
    lookback_bars = int(params.get('lookback_bars', 10))
    lookback_bars = max(5, min(12, lookback_bars))

    # Clamp vol_period to scalping range [3, 10]
    vol_period = int(params.get('vol_period', 5))
    vol_period = max(3, min(10, vol_period))

    out = df.copy()
    close  = out['Close'].astype(float).values
    high   = out['High'].astype(float).values
    low    = out['Low'].astype(float).values
    open_  = out['Open'].astype(float).values
    volume = out['Volume'].astype(float).values if 'Volume' in out.columns else np.ones(len(out))

    n = len(close)

    # --- Rolling intraday high and low over lookback window ---
    roll_high = talib.MAX(high, timeperiod=lookback_bars)
    roll_low  = talib.MIN(low,  timeperiod=lookback_bars)

    # --- Volume surge: current volume vs rolling average ---
    vol_ma = talib.SMA(volume, timeperiod=vol_period)
    vol_surge = np.where(vol_ma > 0, volume / vol_ma, 1.0)

    # --- Short EMA for momentum direction confirmation ---
    ema_fast = talib.EMA(close, timeperiod=5)
    ema_slow = talib.EMA(close, timeperiod=8)

    # --- Previous bar's rolling high/low (1-bar lag of the window high/low) ---
    # Retake: previous close was BELOW rolling high, current close BREAKS ABOVE it
    # Loss:   previous close was ABOVE rolling low,  current close BREAKS BELOW it

    prev_close     = np.empty(n)
    prev_roll_high = np.empty(n)
    prev_roll_low  = np.empty(n)

    prev_close[0]     = np.nan
    prev_roll_high[0] = np.nan
    prev_roll_low[0]  = np.nan

    prev_close[1:]     = close[:-1]
    prev_roll_high[1:] = roll_high[:-1]
    prev_roll_low[1:]  = roll_low[:-1]

    # --- Bull condition ---
    # 1. Current close breaks above the prior rolling high (retake/surge above HOD)
    # 2. Previous close was at or below the prior rolling high (was not already above)
    # 3. Volume surge present (vol_surge > 1.1 = 10% above average)
    # 4. Fast EMA above slow EMA (momentum confirmation)
    retake_bull = (
        (close > prev_roll_high) &
        (prev_close <= prev_roll_high) &
        (vol_surge >= 1.1) &
        (ema_fast > ema_slow)
    )

    # --- Bear condition ---
    # 1. Current close breaks below the prior rolling low (loss/surge below LOD)
    # 2. Previous close was at or above the prior rolling low (was not already below)
    # 3. Volume surge present
    # 4. Fast EMA below slow EMA (momentum confirmation)
    retake_bear = (
        (close < prev_roll_low) &
        (prev_close >= prev_roll_low) &
        (vol_surge >= 1.1) &
        (ema_fast < ema_slow)
    )

    # --- Sustained zone flags (price remains above HOD or below LOD) ---
    bull_zone = (close > roll_high) & (ema_fast > ema_slow)
    bear_zone = (close < roll_low)  & (ema_fast < ema_slow)

    # --- Combined bull/bear boolean ---
    # True on the retake bar OR while price sustains above HOD (bull zone)
    bull_signal = retake_bull | bull_zone
    bear_signal = retake_bear | bear_zone

    # Mask out NaN regions (where talib produced NaN)
    valid = (
        ~np.isnan(roll_high) &
        ~np.isnan(roll_low)  &
        ~np.isnan(ema_fast)  &
        ~np.isnan(ema_slow)  &
        ~np.isnan(vol_ma)    &
        ~np.isnan(prev_close)
    )
    bull_signal = bull_signal & valid
    bear_signal = bear_signal & valid

    # --- Lag helper ---
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty(len(arr), dtype=bool)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr

    idx = out.index

    # --- Assign columns (all shift(1) for lag safety) ---
    out['high_of_day_retake_surge_roll_high'] = pd.Series(_lag1(roll_high), index=idx)
    out['high_of_day_retake_surge_roll_low']  = pd.Series(_lag1(roll_low),  index=idx)
    out['high_of_day_retake_surge_vol_surge'] = pd.Series(_lag1(vol_surge), index=idx)
    out['high_of_day_retake_surge_ema_fast']  = pd.Series(_lag1(ema_fast),  index=idx)
    out['high_of_day_retake_surge_ema_slow']  = pd.Series(_lag1(ema_slow),  index=idx)
    out['high_of_day_retake_surge_retake_bull'] = pd.Series(_lag1(retake_bull), index=idx, dtype=bool)
    out['high_of_day_retake_surge_retake_bear'] = pd.Series(_lag1(retake_bear), index=idx, dtype=bool)
    out['high_of_day_retake_surge_bull']      = pd.Series(_lag1(bull_signal), index=idx, dtype=bool)
    out['high_of_day_retake_surge_bear']      = pd.Series(_lag1(bear_signal), index=idx, dtype=bool)

    return out