"""
features/tv_indicators/ichimoku.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-17T16:01:04
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_ichimoku_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Ichimoku Kinko Hyo cloud system features.
    
    Components:
      - Tenkan-sen (Conversion Line): (9-period high + 9-period low)/2
      - Kijun-sen (Base Line): (26-period high + 26-period low)/2
      - Senkou Span A (Leading Span A): (Tenkan + Kijun)/2, shifted 26 periods forward
      - Senkou Span B (Leading Span B): (52-period high + 52-period low)/2, shifted 26 periods forward
      - Chikou Span (Lagging Span): Close shifted -26 periods backward
      - Cloud: Area between Senkou A and Senkou B
    
    All outputs shift(1) for lag safety.
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["ichimoku"].
    
    Returns:
        df copy with Ichimoku columns added.
    """
    ichimoku_cfg = config.get('tv_indicators', {}).get('ichimoku', {})
    tenkan_period = ichimoku_cfg.get('tenkan', 9)
    kijun_period = ichimoku_cfg.get('kijun', 26)
    senkou_b_period = ichimoku_cfg.get('senkou_b', 52)
    
    out = df.copy()
    close = out["Close"].astype(float).values
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    
    # Tenkan-sen (Conversion Line)
    tenkan_high = talib.MAX(high, timeperiod=tenkan_period)
    tenkan_low = talib.MIN(low, timeperiod=tenkan_period)
    tenkan = (tenkan_high + tenkan_low) / 2.0
    
    # Kijun-sen (Base Line)
    kijun_high = talib.MAX(high, timeperiod=kijun_period)
    kijun_low = talib.MIN(low, timeperiod=kijun_period)
    kijun = (kijun_high + kijun_low) / 2.0
    
    # Senkou Span A (Leading Span A)
    senkou_a = (tenkan + kijun) / 2.0
    
    # Senkou Span B (Leading Span B)
    senkou_b_high = talib.MAX(high, timeperiod=senkou_b_period)
    senkou_b_low = talib.MIN(low, timeperiod=senkou_b_period)
    senkou_b = (senkou_b_high + senkou_b_low) / 2.0
    
    # Chikou Span (Lagging Span)
    chikou = close
    
    # Helper: numpy-level 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty_like(arr)
        out_arr[0] = np.nan
        out_arr[1:] = arr[:-1]
        return out_arr
    
    # Shift Senkou spans forward by 26 periods
    def _shift_forward(arr: np.ndarray, periods: int) -> np.ndarray:
        out_arr = np.full_like(arr, np.nan)
        if len(arr) > periods:
            out_arr[:-periods] = arr[periods:]
        return out_arr
    
    # Shift Chikou span backward by 26 periods
    def _shift_backward(arr: np.ndarray, periods: int) -> np.ndarray:
        out_arr = np.full_like(arr, np.nan)
        if len(arr) > periods:
            out_arr[periods:] = arr[:-periods]
        return out_arr
    
    # Apply shifts
    senkou_a_shifted = _shift_forward(senkou_a, kijun_period)
    senkou_b_shifted = _shift_forward(senkou_b, kijun_period)
    chikou_shifted = _shift_backward(chikou, kijun_period)
    
    # Cloud conditions
    cloud_top = np.maximum(senkou_a_shifted, senkou_b_shifted)
    cloud_bottom = np.minimum(senkou_a_shifted, senkou_b_shifted)
    
    # Price relative to cloud
    price_above_cloud = close > cloud_top
    price_below_cloud = close < cloud_bottom
    price_in_cloud = (~price_above_cloud) & (~price_below_cloud)
    
    # Tenkan/Kijun cross signals
    tk_cross_up = (tenkan > kijun) & (_lag1(tenkan) <= _lag1(kijun))
    tk_cross_down = (tenkan < kijun) & (_lag1(tenkan) >= _lag1(kijun))
    
    # Kumo (Cloud) twist signals
    kumo_twist_up = (senkou_a_shifted > senkou_b_shifted) & (_lag1(senkou_a_shifted) <= _lag1(senkou_b_shifted))
    kumo_twist_down = (senkou_a_shifted < senkou_b_shifted) & (_lag1(senkou_a_shifted) >= _lag1(senkou_b_shifted))
    
    # Add all features with shift(1) for lag safety
    idx = out.index
    
    # Main lines
    out["ichimoku_tenkan"] = pd.Series(_lag1(tenkan), index=idx)
    out["ichimoku_kijun"] = pd.Series(_lag1(kijun), index=idx)
    out["ichimoku_senkou_a"] = pd.Series(_lag1(senkou_a_shifted), index=idx)
    out["ichimoku_senkou_b"] = pd.Series(_lag1(senkou_b_shifted), index=idx)
    out["ichimoku_chikou"] = pd.Series(_lag1(chikou_shifted), index=idx)
    
    # Cloud boundaries
    out["ichimoku_cloud_top"] = pd.Series(_lag1(cloud_top), index=idx)
    out["ichimoku_cloud_bottom"] = pd.Series(_lag1(cloud_bottom), index=idx)
    
    # Price-cloud position
    out["ichimoku_price_above_cloud"] = pd.Series(_lag1(price_above_cloud), index=idx, dtype=bool)
    out["ichimoku_price_below_cloud"] = pd.Series(_lag1(price_below_cloud), index=idx, dtype=bool)
    out["ichimoku_price_in_cloud"] = pd.Series(_lag1(price_in_cloud), index=idx, dtype=bool)
    
    # Signals
    out["ichimoku_tk_cross_up"] = pd.Series(_lag1(tk_cross_up), index=idx, dtype=bool)
    out["ichimoku_tk_cross_down"] = pd.Series(_lag1(tk_cross_down), index=idx, dtype=bool)
    out["ichimoku_kumo_twist_up"] = pd.Series(_lag1(kumo_twist_up), index=idx, dtype=bool)
    out["ichimoku_kumo_twist_down"] = pd.Series(_lag1(kumo_twist_down), index=idx, dtype=bool)
    
    # Cloud color
    out["ichimoku_cloud_bullish"] = pd.Series(_lag1(senkou_a_shifted > senkou_b_shifted), index=idx, dtype=bool)
    out["ichimoku_cloud_bearish"] = pd.Series(_lag1(senkou_a_shifted < senkou_b_shifted), index=idx, dtype=bool)
    
    return out