"""
features/tv_indicators/keltner_channel.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-18T22:45:11
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_keltner_channel_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Keltner Channel features.
    
    Middle band: EMA(close, period)
    Upper band: EMA + (ATR * multiplier)
    Lower band: EMA - (ATR * multiplier)
    
    Signals:
      keltner_channel_bull: Close above upper band (breakout up)
      keltner_channel_bear: Close below lower band (breakout down)
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["keltner_channel"].
    
    Returns:
        df copy with Keltner Channel columns added.
    """
    kc_cfg = config.get('tv_indicators', {}).get('keltner_channel', {})
    period = kc_cfg.get('period', 20)
    atr_mult = kc_cfg.get('atr_mult', 2.0)
    
    out = df.copy()
    close = out["Close"].astype(float).values
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    
    # Middle band (EMA)
    middle = talib.EMA(close, timeperiod=period)
    
    # ATR for band width
    atr = talib.ATR(high, low, close, timeperiod=period)
    
    # Upper and lower bands
    upper = middle + (atr * atr_mult)
    lower = middle - (atr * atr_mult)
    
    # Breakout signals
    bull_breakout = close > upper
    bear_breakout = close < lower
    
    # Helper: numpy-level 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty_like(arr)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr
    
    # Apply lag to all outputs
    idx = out.index
    out["keltner_channel_upper"] = pd.Series(upper, index=idx).shift(1)
    out["keltner_channel_middle"] = pd.Series(middle, index=idx).shift(1)
    out["keltner_channel_lower"] = pd.Series(lower, index=idx).shift(1)
    out["keltner_channel_bull"] = pd.Series(_lag1(bull_breakout), index=idx, dtype=bool)
    out["keltner_channel_bear"] = pd.Series(_lag1(bear_breakout), index=idx, dtype=bool)
    
    return out