"""
features/tv_indicators/linear_regression_velocity_oscillator.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-23T00:23:06
"""
import numpy as np
import pandas as pd
import talib

def add_linear_regression_velocity_oscillator_features(df, config):
    period = config.get('period', 14)
    signal_period = config.get('signal_period', 9)
    
    close_column = config.get('close_column', 'close')
    if close_column not in df.columns:
        close_col = None
        for col in df.columns:
            if col.lower() == close_column.lower():
                close_col = col
                break
        if close_col is None:
            for col in df.columns:
                if close_column.lower() in col.lower():
                    close_col = col
                    break
        if close_col is None:
            raise KeyError(f"Close column not found. Tried: {close_column}")
    else:
        close_col = close_column
    
    close_vals = df[close_col].values
    
    lr_slope = talib.LINEARREG_SLOPE(close_vals, timeperiod=period)
    
    lr_velocity = lr_slope - np.roll(lr_slope, signal_period)
    lr_velocity[:signal_period] = np.nan
    
    df_copy = df.copy()
    df_copy['linear_regression_velocity_oscillator'] = lr_velocity
    df_copy['linear_regression_velocity_oscillator_bull'] = (lr_velocity > 0).astype(bool)
    df_copy['linear_regression_velocity_oscillator_bear'] = (lr_velocity < 0).astype(bool)
    
    df_copy['linear_regression_velocity_oscillator'] = df_copy['linear_regression_velocity_oscillator'].shift(1)
    df_copy['linear_regression_velocity_oscillator_bull'] = df_copy['linear_regression_velocity_oscillator_bull'].shift(1)
    df_copy['linear_regression_velocity_oscillator_bear'] = df_copy['linear_regression_velocity_oscillator_bear'].shift(1)
    
    return df_copy