"""
features/tv_indicators/modified_fisher_transform.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T13:44:37
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_modified_fisher_transform_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Modified Fisher Transform features for scalping (5M charts).
    
    This is a fast oscillator that transforms price into Gaussian-like distribution.
    Bullish when momentum is positive/oversold bounce.
    Bearish when momentum is negative/overbought reversal.
    
    All outputs shift(1) for lag safety.
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["modified_fisher_transform"]
    
    Returns:
        df copy with Modified Fisher Transform columns added.
    """
    # Get parameters with scalping-friendly defaults
    indicator_cfg = config.get('tv_indicators', {}).get('modified_fisher_transform', {})
    period = indicator_cfg.get('period', 8)  # Reduced from default 10 for scalping
    signal_period = indicator_cfg.get('signal_period', 4)  # Reduced from default 5 for scalping
    
    # Ensure scalping constraints
    period = min(max(period, 3), 14)
    signal_period = min(max(signal_period, 3), 5)
    
    out = df.copy()
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    close = out["Close"].astype(float).values
    
    # Calculate median price (H+L)/2
    median_price = (high + low) / 2.0
    
    # Calculate highest high and lowest low over period
    highest_high = talib.MAX(high, timeperiod=period)
    lowest_low = talib.MIN(low, timeperiod=period)
    
    # Calculate normalized price (value between -1 and 1)
    # Avoid division by zero
    price_range = highest_high - lowest_low
    price_range[price_range == 0] = 1e-10
    
    normalized_price = 2 * ((median_price - lowest_low) / price_range - 0.5)
    
    # Constrain normalized price to [-0.999, 0.999] for log calculation
    normalized_price = np.clip(normalized_price, -0.999, 0.999)
    
    # Apply Fisher Transform
    fisher_transform = 0.5 * np.log((1 + normalized_price) / (1 - normalized_price))
    
    # Signal line (EMA of Fisher Transform)
    signal_line = talib.EMA(fisher_transform, timeperiod=signal_period)
    
    # Momentum (difference between Fisher Transform and Signal Line)
    momentum = fisher_transform - signal_line
    
    # Generate signals
    # Bullish: momentum positive AND Fisher Transform is rising from oversold
    oversold_level = -1.5  # Adjusted for scalping
    bull_condition = (momentum > 0) & (fisher_transform > oversold_level)
    
    # Bearish: momentum negative AND Fisher Transform is falling from overbought
    overbought_level = 1.5  # Adjusted for scalping
    bear_condition = (momentum < 0) & (fisher_transform < overbought_level)
    
    # Helper: numpy-level 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty_like(arr)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr
    
    # Apply shift(1) for lag safety
    idx = out.index
    out["modified_fisher_transform_value"] = pd.Series(fisher_transform, index=idx).shift(1)
    out["modified_fisher_transform_signal"] = pd.Series(signal_line, index=idx).shift(1)
    out["modified_fisher_transform_momentum"] = pd.Series(momentum, index=idx).shift(1)
    out["modified_fisher_transform_bull"] = pd.Series(_lag1(bull_condition), index=idx, dtype=bool)
    out["modified_fisher_transform_bear"] = pd.Series(_lag1(bear_condition), index=idx, dtype=bool)
    
    return out