"""
features/tv_indicators/momentum_oscillator_signal.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T13:48:10
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_momentum_oscillator_signal_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Momentum Oscillator with Signal Line for scalping (5M charts).
    
    Logic:
      momentum = Close - Close[momentum_period]
      signal_line = SMA(momentum, signal_period)
      Bullish when momentum crosses above signal line
      Bearish when momentum crosses below signal line
    
    All outputs shift(1) for lag safety.
    """
    out = df.copy()
    close = out["Close"].astype(float).values
    
    # Get parameters with scalping-appropriate defaults
    params = config.get('tv_indicators', {}).get('momentum_oscillator_signal', {})
    momentum_period = params.get('momentum_period', 10)  # Lookback for momentum
    signal_period = params.get('signal_period', 3)       # SMA period for signal line
    
    # Clip periods for scalping (3-14 bars max)
    momentum_period = max(3, min(momentum_period, 14))
    signal_period = max(2, min(signal_period, 5))
    
    # Calculate momentum: Close - Close[momentum_period]
    momentum = close - np.roll(close, momentum_period)
    momentum[:momentum_period] = 0
    
    # Calculate signal line: SMA of momentum
    signal_line = talib.SMA(momentum, timeperiod=signal_period)
    
    # Generate crossover signals
    bull_cross = (momentum > signal_line) & (np.roll(momentum, 1) <= np.roll(signal_line, 1))
    bear_cross = (momentum < signal_line) & (np.roll(momentum, 1) >= np.roll(signal_line, 1))
    
    # Helper for 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty_like(arr, dtype=bool)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr
    
    # Apply shift(1) for lag safety
    idx = out.index
    out["momentum_oscillator_signal_momentum"] = pd.Series(momentum, index=idx).shift(1)
    out["momentum_oscillator_signal_signal"] = pd.Series(signal_line, index=idx).shift(1)
    out["momentum_oscillator_signal_bull"] = pd.Series(_lag1(bull_cross), index=idx, dtype=bool)
    out["momentum_oscillator_signal_bear"] = pd.Series(_lag1(bear_cross), index=idx, dtype=bool)
    
    return out