"""
features/tv_indicators/momentum.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-19T01:44:48
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_momentum_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Classic Momentum Indicator features.
    
    Momentum = Current Close - Close N periods ago
    Bullish when momentum > 0, bearish when momentum < 0.
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config['tv_indicators']['momentum'].
    
    Returns:
        df copy with momentum columns added.
    """
    momentum_cfg = config.get('tv_indicators', {}).get('momentum', {})
    period = momentum_cfg.get('period', 10)
    
    out = df.copy()
    close = out['Close'].astype(float).values
    
    # Calculate momentum: current close - close N periods ago
    momentum = close - np.roll(close, period)
    
    # Raw signals
    momentum_bull_raw = momentum > 0
    momentum_bear_raw = momentum < 0
    
    # Helper: numpy 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        result = np.empty_like(arr, dtype=bool)
        result[0] = False
        result[1:] = arr[:-1]
        return result
    
    # Shift(1) for lag safety
    idx = out.index
    out['momentum_value'] = pd.Series(momentum, index=idx).shift(1)
    out['momentum_bull'] = pd.Series(_lag1(momentum_bull_raw), index=idx, dtype=bool)
    out['momentum_bear'] = pd.Series(_lag1(momentum_bear_raw), index=idx, dtype=bool)
    
    return out