"""
features/tv_indicators/obv.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-19T02:39:00
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_obv_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute On-Balance Volume features.

    OBV is cumulative volume where:
      - Volume added on up days (Close > previous Close)
      - Volume subtracted on down days (Close < previous Close)
      - Volume unchanged on equal days

    Signals:
      obv_bull: Smoothed OBV is rising (current > previous, shift(1))
      obv_bear: Smoothed OBV is falling (current < previous, shift(1))

    Args:
        df: OHLCV DataFrame with Volume column
        config: Full config dict. Reads config["tv_indicators"]["obv"]

    Returns:
        df copy with OBV columns added.
    """
    obv_cfg = config.get("tv_indicators", {}).get("obv", {})
    smooth_period = obv_cfg.get("smooth_period", 10)

    out = df.copy()
    close = out["Close"].astype(float).values
    volume = out["Volume"].astype(float).values

    # Calculate raw OBV using TA-Lib
    obv_raw = talib.OBV(close, volume)

    # Smooth OBV if period > 1
    if smooth_period > 1:
        obv_smooth = talib.EMA(obv_raw, timeperiod=smooth_period)
    else:
        obv_smooth = obv_raw.copy()

    # Create boolean signals for rising/falling OBV
    obv_diff = np.zeros_like(obv_smooth)
    obv_diff[1:] = obv_smooth[1:] - obv_smooth[:-1]

    obv_bull_raw = obv_diff > 0
    obv_bear_raw = obv_diff < 0

    # Helper: numpy-level 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty_like(arr)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr

    # Apply lag(1) to all outputs
    idx = out.index
    out["obv_raw"] = pd.Series(obv_raw, index=idx).shift(1)
    out["obv_smooth"] = pd.Series(obv_smooth, index=idx).shift(1)
    out["obv_bull"] = pd.Series(_lag1(obv_bull_raw), index=idx, dtype=bool)
    out["obv_bear"] = pd.Series(_lag1(obv_bear_raw), index=idx, dtype=bool)

    return out