"""
features/tv_indicators/parabolic_sar.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-17T16:45:51
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_parabolic_sar_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Parabolic SAR (Stop and Reverse) features.
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["parabolic_sar"].
    
    Returns:
        df copy with Parabolic SAR columns added (shifted 1 bar for lag safety).
    """
    psar_cfg = config.get("tv_indicators", {}).get("parabolic_sar", {})
    acceleration = psar_cfg.get("acceleration", 0.02)
    maximum = psar_cfg.get("maximum", 0.2)
    
    out = df.copy()
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    
    # Compute Parabolic SAR
    sar = talib.SAR(high, low, acceleration=acceleration, maximum=maximum)
    
    # Create boolean signals (bearish when SAR > Close)
    close = out["Close"].astype(float).values
    bearish_raw = sar > close
    bullish_raw = ~bearish_raw
    
    # Helper: numpy-level 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty_like(arr)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr
    
    idx = out.index
    out["parabolic_sar"] = pd.Series(sar, index=idx).shift(1)
    out["parabolic_sar_bull"] = pd.Series(_lag1(bullish_raw), index=idx, dtype=bool)
    out["parabolic_sar_bear"] = pd.Series(_lag1(bearish_raw), index=idx, dtype=bool)
    
    return out