"""
features/tv_indicators/rate_of_change.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T18:44:24
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_rate_of_change_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute rate_of_change oscillator features for 5M scalping.
    
    Calculates percentage price change over short period (3-14 bars).
    Bullish when ROC > 0 (positive momentum).
    Bearish when ROC < 0 (negative momentum).
    
    All outputs shift(1) for lag safety.
    """
    tv_cfg = config.get('tv_indicators', {})
    roc_cfg = tv_cfg.get('rate_of_change', {})
    
    # Use scalping-appropriate period (3-14 bars for 5M)
    period = min(max(roc_cfg.get('period', 10), 3), 14)
    
    out = df.copy()
    close = out["Close"].astype(float).values
    
    # Calculate Rate of Change: ((close - close_n_periods_ago) / close_n_periods_ago) * 100
    roc = talib.ROC(close, timeperiod=period)
    
    # Bullish/Bearish conditions
    roc_bull = roc > 0
    roc_bear = roc < 0
    
    # Shift(1) for lag safety
    idx = out.index
    out["rate_of_change"] = pd.Series(roc, index=idx).shift(1)
    out["rate_of_change_bull"] = pd.Series(roc_bull, index=idx).shift(1)
    out["rate_of_change_bear"] = pd.Series(roc_bear, index=idx).shift(1)
    
    return out