"""
features/tv_indicators/relative_vigor_index.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T23:56:08
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any

def add_relative_vigor_index_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Relative Vigor Index (RVI) features for scalping.
    
    RVI = SMA((Close - Open) / (High - Low), period)
    Signal = SMA(RVI, signal_period)
    
    Signals:
      relative_vigor_index_bull: RVI > Signal (momentum positive)
      relative_vigor_index_bear: RVI < Signal (momentum negative)
    
    All outputs shift(1) for lag safety.
    """
    out = df.copy()
    
    # Get parameters with scalping-appropriate defaults
    indicator_config = config.get('tv_indicators', {}).get('relative_vigor_index', {})
    period = int(indicator_config.get('period', 8))  # Default 8 for scalping
    signal_period = int(indicator_config.get('signal_period', 3))  # Default 3 for scalping
    
    # Ensure scalping constraints
    period = min(max(period, 3), 14)
    signal_period = min(max(signal_period, 2), 5)
    
    close = out["Close"].astype(float).values
    open_ = out["Open"].astype(float).values
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    
    # Calculate numerator and denominator with zero division protection
    numerator = close - open_
    denominator = high - low
    denominator = np.where(denominator == 0, 1e-10, denominator)
    
    # RVI calculation
    rvi = talib.SMA(numerator / denominator, timeperiod=period)
    signal = talib.SMA(rvi, timeperiod=signal_period)
    
    # Generate signals
    bull_raw = rvi > signal
    bear_raw = rvi < signal
    
    # Shift(1) for lag safety
    idx = out.index
    out["relative_vigor_index_rvi"] = pd.Series(rvi, index=idx).shift(1)
    out["relative_vigor_index_signal"] = pd.Series(signal, index=idx).shift(1)
    out["relative_vigor_index_bull"] = pd.Series(bull_raw, index=idx).shift(1)
    out["relative_vigor_index_bear"] = pd.Series(bear_raw, index=idx).shift(1)
    
    return out