"""
features/tv_indicators/rsi_modified_cmf_fusion.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-23T00:09:44
"""
import numpy as np
import pandas as pd
import talib

def add_rsi_modified_cmf_fusion_features(df, config):
    df = df.copy()
    
    rsi_period = config.get('rsi_period', 14)
    cmf_period = config.get('cmf_period', 20)
    rsi_overbought = config.get('rsi_overbought', 70)
    rsi_oversold = config.get('rsi_oversold', 30)
    cmf_threshold = config.get('cmf_threshold', 0.05)
    
    if 'close' in df.columns:
        rsi = talib.RSI(df['close'], timeperiod=rsi_period)
    else:
        rsi = pd.Series(np.nan, index=df.index)
    
    if all(col in df.columns for col in ['high', 'low', 'close', 'volume']):
        cmf = talib.ADOSC(df['high'], df['low'], df['close'], df['volume'], 
                          fastperiod=3, slowperiod=10)
    else:
        cmf = pd.Series(np.nan, index=df.index)
    
    rsi_bull_condition = (rsi > rsi_oversold) & (rsi < rsi_overbought)
    cmf_bull_condition = cmf > cmf_threshold
    df['rsi_modified_cmf_fusion_bull'] = (rsi_bull_condition & cmf_bull_condition).shift(1)
    
    rsi_bear_condition = (rsi > rsi_overbought) | (rsi < rsi_oversold)
    cmf_bear_condition = cmf < -cmf_threshold
    df['rsi_modified_cmf_fusion_bear'] = (rsi_bear_condition & cmf_bear_condition).shift(1)
    
    return df