"""
features/tv_indicators/rsi_t3_mtf_oscillator.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T17:50:01
"""
import numpy as np
import pandas as pd
import talib

def add_rsi_t3_mtf_oscillator_features(df, config) -> pd.DataFrame:
    df = df.copy()
    
    close_column = 'close'
    if 'close_column' in config:
        close_column = config['close_column']
    elif 'close' in df.columns:
        close_column = 'close'
    elif 'Close' in df.columns:
        close_column = 'Close'
    else:
        for col in df.columns:
            if col.lower() == 'close':
                close_column = col
                break
    
    close_series = df[close_column]
    
    rsi_period = config.get('rsi_period', 14)
    rsi_overbought = config.get('rsi_overbought', 70)
    rsi_oversold = config.get('rsi_oversold', 30)
    t3_period = config.get('t3_period', 5)
    t3_vfactor = config.get('t3_vfactor', 0.7)
    
    rsi = talib.RSI(close_series, timeperiod=rsi_period)
    
    ema1 = talib.EMA(rsi, timeperiod=t3_period)
    ema2 = talib.EMA(ema1, timeperiod=t3_period)
    ema3 = talib.EMA(ema2, timeperiod=t3_period)
    ema4 = talib.EMA(ema3, timeperiod=t3_period)
    ema5 = talib.EMA(ema4, timeperiod=t3_period)
    ema6 = talib.EMA(ema5, timeperiod=t3_period)
    
    c1 = -t3_vfactor * t3_vfactor * t3_vfactor
    c2 = 3 * t3_vfactor * t3_vfactor + 3 * t3_vfactor * t3_vfactor * t3_vfactor
    c3 = -6 * t3_vfactor * t3_vfactor - 3 * t3_vfactor - 3 * t3_vfactor * t3_vfactor * t3_vfactor
    c4 = 1 + 3 * t3_vfactor + t3_vfactor * t3_vfactor * t3_vfactor + 3 * t3_vfactor * t3_vfactor
    
    t3_rsi = c1 * ema6 + c2 * ema5 + c3 * ema4 + c4 * ema3
    
    df['rsi_t3_mtf_oscillator_t3_rsi'] = t3_rsi.shift(1)
    df['rsi_t3_mtf_oscillator_bull'] = (t3_rsi.shift(1) < rsi_oversold)
    df['rsi_t3_mtf_oscillator_bear'] = (t3_rsi.shift(1) > rsi_overbought)
    
    return df