"""
features/tv_indicators/short_term_z_score.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-23T00:50:04
"""
import numpy as np
import pandas as pd
import talib

def add_short_term_z_score_features(df, config):
    df = df.copy()
    
    lookback = config.get('lookback', 20)
    bull_threshold = config.get('bull_threshold', 1.0)
    bear_threshold = config.get('bear_threshold', -1.0)
    
    if 'close' not in df.columns:
        df['short_term_z_score_z'] = np.nan
    else:
        rolling_mean = df['close'].rolling(window=lookback).mean()
        rolling_std = df['close'].rolling(window=lookback).std()
        df['short_term_z_score_z'] = (df['close'] - rolling_mean) / rolling_std
    
    df['short_term_z_score_bull'] = df['short_term_z_score_z'] > bull_threshold
    df['short_term_z_score_bear'] = df['short_term_z_score_z'] < bear_threshold
    
    output_cols = ['short_term_z_score_z', 'short_term_z_score_bull', 'short_term_z_score_bear']
    for col in output_cols:
        df[col] = df[col].shift(1)
        if col in ['short_term_z_score_bull', 'short_term_z_score_bear']:
            df[col] = df[col].fillna(False).astype(bool)
        else:
            df[col] = df[col].astype(float)
    
    return df