"""
features/tv_indicators/squeeze_momentum.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-17T15:56:33
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_squeeze_momentum_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Squeeze Momentum indicator features.
    
    Logic:
    1. Calculate Bollinger Bands (BB) and Keltner Channels (KC)
    2. Detect squeeze when BB is inside KC
    3. Compute momentum histogram based on price position relative to BB/KC
    4. All outputs shift(1) for lag safety
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["squeeze_momentum"]
    
    Returns:
        df copy with squeeze_momentum columns added
    """
    # Get parameters
    params = config.get('tv_indicators', {}).get('squeeze_momentum', {})
    bb_length = params.get('bb_length', 20)
    kc_length = params.get('kc_length', 20)
    kc_mult = params.get('kc_mult', 1.5)
    
    out = df.copy()
    close = out["Close"].astype(float).values
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    
    # Calculate Bollinger Bands
    bb_middle = talib.SMA(close, timeperiod=bb_length)
    bb_std = talib.STDDEV(close, timeperiod=bb_length)
    bb_upper = bb_middle + 2 * bb_std
    bb_lower = bb_middle - 2 * bb_std
    
    # Calculate Keltner Channels
    typical_price = (high + low + close) / 3.0
    kc_middle = talib.SMA(typical_price, timeperiod=kc_length)
    
    atr = talib.ATR(high, low, close, timeperiod=kc_length)
    kc_upper = kc_middle + kc_mult * atr
    kc_lower = kc_middle - kc_mult * atr
    
    # Squeeze detection
    squeeze_on = (bb_upper < kc_upper) & (bb_lower > kc_lower)
    
    # Momentum calculation (Lazybear style)
    # Histogram based on price position relative to BB/KC
    bb_width = bb_upper - bb_lower
    kc_width = kc_upper - kc_lower
    
    # Normalized momentum
    momentum_raw = (close - bb_middle) / bb_width * 100
    
    # Histogram coloring logic
    momentum_hist = momentum_raw.copy()
    
    # Helper: numpy-level 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty_like(arr)
        out_arr[0] = arr[0]
        out_arr[1:] = arr[:-1]
        return out_arr
    
    # Bull/bear: momentum direction + squeeze released
    bull_raw = (~squeeze_on) & (momentum_raw > 0)
    bear_raw = (~squeeze_on) & (momentum_raw < 0)

    # Shift all outputs for lag safety
    idx = out.index
    out["squeeze_momentum_squeeze_on"] = pd.Series(_lag1(squeeze_on), index=idx, dtype=bool)
    out["squeeze_momentum_momentum"] = pd.Series(_lag1(momentum_raw), index=idx)
    out["squeeze_momentum_histogram"] = pd.Series(_lag1(momentum_hist), index=idx)
    out["squeeze_momentum_bb_upper"] = pd.Series(_lag1(bb_upper), index=idx)
    out["squeeze_momentum_bb_middle"] = pd.Series(_lag1(bb_middle), index=idx)
    out["squeeze_momentum_bb_lower"] = pd.Series(_lag1(bb_lower), index=idx)
    out["squeeze_momentum_kc_upper"] = pd.Series(_lag1(kc_upper), index=idx)
    out["squeeze_momentum_kc_middle"] = pd.Series(_lag1(kc_middle), index=idx)
    out["squeeze_momentum_kc_lower"] = pd.Series(_lag1(kc_lower), index=idx)
    out["squeeze_momentum_bull"] = pd.Series(_lag1(bull_raw.astype(bool)), index=idx, dtype=bool)
    out["squeeze_momentum_bear"] = pd.Series(_lag1(bear_raw.astype(bool)), index=idx, dtype=bool)

    return out