"""
features/tv_indicators/squeeze_momentum.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-18T22:23:54
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any

def add_squeeze_momentum_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    cfg = config.get("tv_indicators", {}).get("squeeze_momentum", {})
    bb_length = cfg.get("bb_length", 20)
    kc_length = cfg.get("kc_length", 20)
    kc_mult = cfg.get("kc_mult", 1.5)
    
    out = df.copy()
    close = out["Close"].astype(float).values
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    
    # Bollinger Bands (2 std dev)
    bb_upper, bb_middle, bb_lower = talib.BBANDS(
        close, timeperiod=bb_length, nbdevup=2, nbdevdn=2
    )
    
    # Keltner Channel
    typical = (high + low + close) / 3.0
    kc_middle = talib.EMA(typical, timeperiod=kc_length)
    atr = talib.ATR(high, low, close, timeperiod=kc_length)
    kc_upper = kc_middle + (atr * kc_mult)
    kc_lower = kc_middle - (atr * kc_mult)
    
    # Squeeze condition
    squeeze = (bb_upper < kc_upper) & (bb_lower > kc_lower)
    
    # Momentum histogram (Lazybear style)
    ema12 = talib.EMA(close, timeperiod=12)
    ema26 = talib.EMA(close, timeperiod=26)
    momentum_raw = ema12 - ema26
    atr12 = talib.ATR(high, low, close, timeperiod=12)
    histogram = (momentum_raw / atr12) * 100
    
    # Signal conditions
    bull = (histogram > 0) & (~squeeze)
    bear = (histogram < 0) & (~squeeze)
    
    # Shift all outputs by 1 for lag safety
    idx = out.index
    out["squeeze_momentum_bull"] = pd.Series(bull, index=idx).shift(1).astype(bool)
    out["squeeze_momentum_bear"] = pd.Series(bear, index=idx).shift(1).astype(bool)
    out["squeeze_momentum_squeeze"] = pd.Series(squeeze, index=idx).shift(1).astype(bool)
    out["squeeze_momentum_histogram"] = pd.Series(histogram, index=idx).shift(1)
    out["squeeze_momentum_bb_width"] = pd.Series(bb_upper - bb_lower, index=idx).shift(1)
    
    return out