"""
features/tv_indicators/stochastic_rsi.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T19:35:52
"""
import numpy as np
import pandas as pd
import talib

def add_stochastic_rsi_features(df, config):
    df = df.copy()
    
    close_col = None
    for col in df.columns:
        if col.lower() == 'close':
            close_col = col
            break
    if close_col is None:
        raise KeyError("No 'close' column found in DataFrame")
    
    rsi_length = config.get('rsi_length', 14)
    stoch_length = config.get('stoch_length', 14)
    k_smooth = config.get('k_smooth', 3)
    d_smooth = config.get('d_smooth', 3)
    
    rsi = talib.RSI(df[close_col].astype(float), timeperiod=rsi_length)
    min_rsi = talib.MIN(rsi, timeperiod=stoch_length)
    max_rsi = talib.MAX(rsi, timeperiod=stoch_length)
    
    raw_stoch = np.where(
        max_rsi - min_rsi != 0,
        100 * (rsi - min_rsi) / (max_rsi - min_rsi),
        50
    )
    
    smooth_stoch = talib.SMA(raw_stoch, timeperiod=k_smooth)
    final_stoch = talib.SMA(smooth_stoch, timeperiod=d_smooth)
    
    smooth_series = pd.Series(smooth_stoch, index=df.index)
    final_series = pd.Series(final_stoch, index=df.index)
    
    df['stochastic_rsi_k'] = smooth_series.shift(1)
    df['stochastic_rsi_d'] = final_series.shift(1)
    
    df['stochastic_rsi_bull'] = ((smooth_series > final_series) & 
                                 (smooth_series.shift(1) <= final_series.shift(1))).shift(1)
    df['stochastic_rsi_bear'] = ((smooth_series < final_series) & 
                                 (smooth_series.shift(1) >= final_series.shift(1))).shift(1)
    
    return df