"""
features/tv_indicators/stochastic.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-19T02:04:18
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_stochastic_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Stochastic Oscillator features.

    Calculates %K and %D lines with custom smoothing periods.
    Bullish when %K > %D (momentum positive)
    Bearish when %K < %D (momentum negative)

    Args:
        df:     OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["stochastic"].

    Returns:
        df copy with Stochastic columns added.
    """
    stoch_cfg = config.get('tv_indicators', {}).get('stochastic', {})
    period = stoch_cfg.get("period", 14)
    k_smooth = stoch_cfg.get("k_smooth", 3)
    d_smooth = stoch_cfg.get("d_smooth", 3)

    out = df.copy()
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    close = out["Close"].astype(float).values

    # Calculate Stochastic using TA-Lib
    slowk, slowd = talib.STOCH(
        high, low, close,
        fastk_period=period,
        slowk_period=k_smooth,
        slowk_matype=0,  # SMA for %K
        slowd_period=d_smooth,
        slowd_matype=0   # SMA for %D
    )

    # Create boolean conditions
    bull_condition = slowk > slowd
    bear_condition = slowk < slowd

    # Helper: numpy-level 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        shifted = np.empty_like(arr)
        shifted[0] = np.nan
        shifted[1:] = arr[:-1]
        return shifted

    # Apply lag to avoid lookahead bias
    out["stochastic_slowk"] = _lag1(slowk)
    out["stochastic_slowd"] = _lag1(slowd)
    out["stochastic_bull"] = _lag1(bull_condition).astype(bool)
    out["stochastic_bear"] = _lag1(bear_condition).astype(bool)

    return out