"""
features/tv_indicators/stochastic_rsi.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-17T16:31:08
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_stochastic_rsi_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Stochastic RSI features.
    
    Logic:
      1. Calculate RSI of Close with rsi_length
      2. Apply Stochastic formula on RSI values over stoch_length periods
      3. Smooth with k_smooth periods SMA for %K
      4. Smooth %K with d_smooth periods SMA for %D
      5. Generate overbought/oversold signals at 80/20 levels
    
    All outputs shift(1) for lag safety.
    
    Args:
        df:     OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["stochastic_rsi"]
    
    Returns:
        df copy with Stochastic RSI columns added.
    """
    out = df.copy()
    cfg = config.get("tv_indicators", {}).get("stochastic_rsi", {})
    
    # Parameters
    rsi_length  = cfg.get("rsi_length", 14)
    stoch_length = cfg.get("stoch_length", 14)
    k_smooth    = cfg.get("k_smooth", 3)
    d_smooth    = cfg.get("d_smooth", 3)
    
    close = out["Close"].astype(float).values
    
    # 1. Calculate RSI
    rsi = talib.RSI(close, timeperiod=rsi_length)
    
    # Handle NaN values
    rsi_valid = ~np.isnan(rsi)
    if not rsi_valid.any():
        # Initialize all output columns with NaN/False
        out["stochastic_rsi_k"] = np.nan
        out["stochastic_rsi_d"] = np.nan
        out["stochastic_rsi_overbought"] = False
        out["stochastic_rsi_oversold"] = False
        out["stochastic_rsi_buy"] = False
        out["stochastic_rsi_sell"] = False
        return out
    
    # 2. Calculate Stochastic of RSI
    stoch_k_raw = np.full_like(rsi, np.nan)
    
    for i in range(stoch_length - 1, len(rsi)):
        if i < stoch_length - 1:
            continue
            
        rsi_window = rsi[i - (stoch_length - 1):i + 1]
        
        if np.all(np.isnan(rsi_window)):
            continue
            
        lowest = np.nanmin(rsi_window)
        highest = np.nanmax(rsi_window)
        
        if highest - lowest == 0:
            stoch_k_raw[i] = 0
        else:
            stoch_k_raw[i] = 100 * (rsi[i] - lowest) / (highest - lowest)
    
    # 3. Smooth %K with SMA
    stoch_k = talib.SMA(stoch_k_raw, timeperiod=k_smooth)
    
    # 4. Smooth %D with SMA
    stoch_d = talib.SMA(stoch_k, timeperiod=d_smooth)
    
    # 5. Generate signals
    overbought = stoch_k > 80
    oversold = stoch_k < 20
    
    # Buy: %K crosses above %D while %K is oversold
    k_above_d = stoch_k > stoch_d
    k_below_d_prev = np.concatenate([[False], (stoch_k[:-1] <= stoch_d[:-1])])
    buy_raw = k_above_d & k_below_d_prev & oversold
    
    # Sell: %K crosses below %D while %K is overbought
    k_below_d = stoch_k < stoch_d
    k_above_d_prev = np.concatenate([[False], (stoch_k[:-1] >= stoch_d[:-1])])
    sell_raw = k_below_d & k_above_d_prev & overbought
    
    # Shift all outputs by 1 for lag safety
    idx = out.index
    out["stochastic_rsi_k"] = pd.Series(stoch_k, index=idx).shift(1)
    out["stochastic_rsi_d"] = pd.Series(stoch_d, index=idx).shift(1)
    out["stochastic_rsi_overbought"] = pd.Series(overbought, index=idx).shift(1)
    out["stochastic_rsi_oversold"] = pd.Series(oversold, index=idx).shift(1)
    out["stochastic_rsi_buy"] = pd.Series(buy_raw, index=idx).shift(1)
    out["stochastic_rsi_sell"] = pd.Series(sell_raw, index=idx).shift(1)
    
    return out