"""
features/tv_indicators/supertrend.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-17T16:13:17
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_supertrend_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Supertrend ATR-based trailing stop indicator.

    Outputs:
      supertrend_line: Current supertrend value (shift(1))
      supertrend_direction: 1 for bullish (above), -1 for bearish (below) (shift(1))
      supertrend_buy: Signal when direction changes from -1 to 1 (shift(1))
      supertrend_sell: Signal when direction changes from 1 to -1 (shift(1))

    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config['tv_indicators']['supertrend'].

    Returns:
        df copy with Supertrend columns added.
    """
    # Get parameters with defaults
    st_cfg = config.get('tv_indicators', {}).get('supertrend', {})
    period = st_cfg.get('period', 10)
    multiplier = st_cfg.get('multiplier', 3.0)

    out = df.copy()
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    close = out["Close"].astype(float).values

    # Calculate HL2 and ATR
    hl2 = (high + low) / 2
    atr = talib.ATR(high, low, close, timeperiod=period)

    # Basic upper and lower bands
    basic_upper = hl2 + (multiplier * atr)
    basic_lower = hl2 - (multiplier * atr)

    # Initialize arrays for final upper/lower bands and direction
    final_upper = np.zeros_like(close)
    final_lower = np.zeros_like(close)
    direction = np.zeros_like(close)

    # First bar initialization
    final_upper[0] = basic_upper[0]
    final_lower[0] = basic_lower[0]
    direction[0] = 1 if close[0] <= final_upper[0] else -1

    # Iterative calculation for remaining bars
    for i in range(1, len(close)):
        # Update final upper band
        if basic_upper[i] < final_upper[i-1] or close[i-1] > final_upper[i-1]:
            final_upper[i] = basic_upper[i]
        else:
            final_upper[i] = final_upper[i-1]

        # Update final lower band
        if basic_lower[i] > final_lower[i-1] or close[i-1] < final_lower[i-1]:
            final_lower[i] = basic_lower[i]
        else:
            final_lower[i] = final_lower[i-1]

        # Determine direction
        if direction[i-1] == 1:
            if close[i] <= final_upper[i]:
                direction[i] = 1
            else:
                direction[i] = -1
        else:  # direction[i-1] == -1
            if close[i] >= final_lower[i]:
                direction[i] = -1
            else:
                direction[i] = 1

    # Calculate supertrend line
    supertrend_line = np.where(direction == 1, final_lower, final_upper)

    # Transition signals
    buy_raw = (direction == 1) & (np.roll(direction, 1) == -1)
    sell_raw = (direction == -1) & (np.roll(direction, 1) == 1)
    # Fix first element (rolled value is invalid)
    buy_raw[0] = False
    sell_raw[0] = False

    # Apply shift(1) for lag safety
    idx = out.index
    out["supertrend_line"] = pd.Series(supertrend_line, index=idx).shift(1)
    out["supertrend_direction"] = pd.Series(direction, index=idx).shift(1)
    out["supertrend_buy"] = pd.Series(buy_raw, index=idx).shift(1).astype(bool)
    out["supertrend_sell"] = pd.Series(sell_raw, index=idx).shift(1).astype(bool)

    return out