"""
features/tv_indicators/trix.py - Auto-generated TV indicator module.
Generated by tv_research_loop on 2026-03-18T23:12:10
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_trix_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute TRIX (Triple Exponential Average) momentum indicator.
    
    Formula:
      1. EMA1 = EMA(Close, period)
      2. EMA2 = EMA(EMA1, period)
      3. EMA3 = EMA(EMA2, period)
      4. TRIX = ((EMA3 - EMA3[1]) / EMA3[1]) * 100
      5. Signal = EMA(TRIX, signal_period)
    
    Signals:
      trix_bull: TRIX > Signal (momentum positive)
      trix_bear: TRIX < Signal (momentum negative)
    
    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["trix"].
    
    Returns:
        df copy with TRIX columns added (all shift(1) for lag safety).
    """
    trix_cfg = config.get("tv_indicators", {}).get("trix", {})
    period = trix_cfg.get("period", 18)
    signal_period = trix_cfg.get("signal", 9)
    
    out = df.copy()
    close = out["Close"].astype(float).values
    
    # Triple EMA calculation
    ema1 = talib.EMA(close, timeperiod=period)
    ema2 = talib.EMA(ema1, timeperiod=period)
    ema3 = talib.EMA(ema2, timeperiod=period)
    
    # TRIX = percent rate of change of triple EMA
    trix_line = np.zeros_like(ema3)
    trix_line[1:] = ((ema3[1:] - ema3[:-1]) / ema3[:-1]) * 100
    
    # Signal line (EMA of TRIX)
    signal_line = talib.EMA(trix_line, timeperiod=signal_period)
    
    # Boolean conditions (before shift)
    trix_bull_raw = trix_line > signal_line
    trix_bear_raw = trix_line < signal_line
    
    # Helper: numpy-level 1-bar lag
    def _lag1(arr: np.ndarray) -> np.ndarray:
        out_arr = np.empty_like(arr)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr
    
    # Shift(1) all outputs for lag safety
    idx = out.index
    out["trix_line"] = pd.Series(trix_line, index=idx).shift(1)
    out["trix_signal"] = pd.Series(signal_line, index=idx).shift(1)
    out["trix_bull"] = pd.Series(_lag1(trix_bull_raw), index=idx, dtype=bool)
    out["trix_bear"] = pd.Series(_lag1(trix_bear_raw), index=idx, dtype=bool)
    
    return out