"""
features/tv_indicators/trix_oscillator.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T22:07:05
"""
import numpy as np
import pandas as pd
import talib

def add_trix_oscillator_features(df, config):
    # Create a copy of the DataFrame to avoid modifying the original
    df = df.copy()
    
    # Get the period from config, default to 15
    period = config.get('period', 15)
    
    # Get close column name from config, try common variants
    close_col = config.get('close_column', None)
    
    if close_col is None:
        # Try common column name variations
        if 'close' in df.columns:
            close_col = 'close'
        elif 'Close' in df.columns:
            close_col = 'Close'
        else:
            raise KeyError("Could not find a column for close prices. Please specify in config with key 'close_column'.")
    
    # Calculate TRIX
    trix = talib.TRIX(df[close_col], timeperiod=period)
    
    # Apply lag to avoid lookahead bias
    trix_lagged = trix.shift(1)
    
    # Add the TRIX oscillator column (with underscore at end as per prefix requirement)
    df['trix_oscillator_'] = trix_lagged
    
    # Create boolean columns based on lagged values
    df['trix_oscillator_bull'] = (trix_lagged > 0)
    df['trix_oscillator_bear'] = (trix_lagged < 0)
    
    return df