"""
features/tv_indicators/tsi_impulse_breakout.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-24T18:03:03
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_tsi_impulse_breakout_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute TSI Impulse Breakout features for scalping on 5M charts.

    True Strength Index (TSI) measures momentum using double-smoothed price changes.
    This implementation uses short periods suitable for scalping.

    Zones / Signals:
      tsi_impulse_breakout_bull: TSI crosses above signal line AND TSI > 0 (bullish momentum)
      tsi_impulse_breakout_bear: TSI crosses below signal line AND TSI < 0 (bearish momentum)

    All outputs are shift(1) for lag safety.

    Args:
        df:     OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["tsi_impulse_breakout"].

    Returns:
        df copy with tsi_impulse_breakout_ columns added.
    """
    params = config.get('tv_indicators', {}).get('tsi_impulse_breakout', {})
    long_period   = int(params.get('long_period',   8))
    short_period  = int(params.get('short_period',  4))
    signal_period = int(params.get('signal_period', 3))

    # Clamp to scalping-safe ranges
    long_period   = max(3, min(long_period,   14))
    short_period  = max(3, min(short_period,  10))
    signal_period = max(2, min(signal_period,  5))

    out   = df.copy()
    close = out["Close"].astype(float).values
    n     = len(close)

    # --- True Strength Index (TSI) ---
    # 1) Price change
    pc = np.empty(n)
    pc[0] = 0.0
    pc[1:] = close[1:] - close[:-1]

    # 2) Double-smoothed momentum: EMA(EMA(pc, long), short)
    ema1_pc = talib.EMA(pc,        timeperiod=long_period)
    ema2_pc = talib.EMA(ema1_pc,   timeperiod=short_period)

    # 3) Double-smoothed absolute momentum: EMA(EMA(|pc|, long), short)
    abs_pc  = np.abs(pc)
    ema1_abs = talib.EMA(abs_pc,   timeperiod=long_period)
    ema2_abs = talib.EMA(ema1_abs, timeperiod=short_period)

    # 4) TSI = 100 * double_smooth_pc / double_smooth_abs_pc
    tsi = np.where(ema2_abs != 0.0, 100.0 * ema2_pc / ema2_abs, 0.0)

    # 5) Signal line: EMA of TSI
    signal = talib.EMA(tsi, timeperiod=signal_period)

    # --- Breakout / Impulse detection (raw, pre-shift) ---
    # Bull: TSI crosses above signal AND TSI > 0
    # Bear: TSI crosses below signal AND TSI < 0

    tsi_above_signal = tsi > signal
    tsi_below_signal = tsi < signal

    def _lag1(arr: np.ndarray) -> np.ndarray:
        result = np.empty(len(arr), dtype=bool)
        result[0] = False
        result[1:] = arr[:-1]
        return result

    # Cross above: currently above, previously below or equal
    cross_above = tsi_above_signal & ~_lag1(tsi_above_signal)
    # Cross below: currently below, previously above or equal
    cross_below = tsi_below_signal & ~_lag1(tsi_below_signal)

    bull_raw = cross_above & (tsi > 0)
    bear_raw = cross_below & (tsi < 0)

    # --- Directional breakout confirmation via price channel ---
    # Bullish breakout: close > highest high of last lookback bars (breakout up)
    # Bearish breakout: close < lowest low  of last lookback bars (breakout down)
    lookback = min(long_period, 8)

    highest_high = talib.MAX(out["High"].astype(float).values, timeperiod=lookback)
    lowest_low   = talib.MIN(out["Low"].astype(float).values,  timeperiod=lookback)

    # Shift price channel by 1 to avoid lookahead (compare close to previous channel)
    prev_highest = np.empty(n)
    prev_highest[0] = np.nan
    prev_highest[1:] = highest_high[:-1]

    prev_lowest = np.empty(n)
    prev_lowest[0] = np.nan
    prev_lowest[1:] = lowest_low[:-1]

    price_breakout_up   = close > prev_highest
    price_breakout_down = close < prev_lowest

    # Combined signal: TSI impulse + price breakout
    bull_impulse_raw = bull_raw & price_breakout_up
    bear_impulse_raw = bear_raw & price_breakout_down

    # Also include pure TSI trend columns (zone-level, not just cross)
    tsi_bull_zone_raw = (tsi > signal) & (tsi > 0)
    tsi_bear_zone_raw = (tsi < signal) & (tsi < 0)

    # --- Shift all outputs by 1 bar for lag safety ---
    idx = out.index

    out["tsi_impulse_breakout_tsi"]         = pd.Series(tsi,    index=idx).shift(1)
    out["tsi_impulse_breakout_signal"]       = pd.Series(signal, index=idx).shift(1)

    out["tsi_impulse_breakout_bull"]         = pd.Series(_lag1(bull_impulse_raw),  index=idx, dtype=bool)
    out["tsi_impulse_breakout_bear"]         = pd.Series(_lag1(bear_impulse_raw),  index=idx, dtype=bool)

    out["tsi_impulse_breakout_zone_bull"]    = pd.Series(_lag1(tsi_bull_zone_raw), index=idx, dtype=bool)
    out["tsi_impulse_breakout_zone_bear"]    = pd.Series(_lag1(tsi_bear_zone_raw), index=idx, dtype=bool)

    out["tsi_impulse_breakout_cross_above"]  = pd.Series(_lag1(cross_above),       index=idx, dtype=bool)
    out["tsi_impulse_breakout_cross_below"]  = pd.Series(_lag1(cross_below),       index=idx, dtype=bool)

    return out