"""
features/tv_indicators/volatility_ratio_ma_crossover.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-23T00:34:11
"""
import numpy as np
import pandas as pd
import talib

def add_volatility_ratio_ma_crossover_features(df, config):
    out = df.copy()
    
    fast_ma = config.get("fast_ma", 5)
    slow_ma = config.get("slow_ma", 12)
    atr_period = config.get("atr_period", 10)
    threshold_multiplier = config.get("threshold_multiplier", 1.5)
    
    close = out["Close"].astype(float).values
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    
    fast_ma_vals = talib.EMA(close, timeperiod=fast_ma)
    slow_ma_vals = talib.EMA(close, timeperiod=slow_ma)
    
    ma_diff = fast_ma_vals - slow_ma_vals
    atr_vals = talib.ATR(high, low, close, timeperiod=atr_period)
    
    volatility_ratio = ma_diff / atr_vals
    threshold = threshold_multiplier
    
    above_threshold = volatility_ratio > threshold
    below_neg_threshold = volatility_ratio < -threshold
    
    prev_above = np.roll(above_threshold, 1)
    prev_above[0] = False
    prev_below = np.roll(below_neg_threshold, 1)
    prev_below[0] = False
    
    bull_raw = above_threshold & ~prev_above
    bear_raw = below_neg_threshold & ~prev_below
    
    def _lag1(arr):
        out_arr = np.empty_like(arr)
        out_arr[0] = False
        out_arr[1:] = arr[:-1]
        return out_arr
    
    out["volatility_ratio_ma_crossover_ratio"] = pd.Series(_lag1(volatility_ratio), index=out.index)
    out["volatility_ratio_ma_crossover_bull"] = pd.Series(_lag1(bull_raw), index=out.index, dtype=bool)
    out["volatility_ratio_ma_crossover_bear"] = pd.Series(_lag1(bear_raw), index=out.index, dtype=bool)
    
    return out