"""
features/tv_indicators/volume_weighted_rsi.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T13:44:05
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any


def add_volume_weighted_rsi_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Volume Weighted RSI features for 5M scalping.
    
    Logic:
    1. Calculate standard RSI
    2. Weight RSI by recent volume spikes (volume / SMA(volume))
    3. Generate signals when weighted RSI crosses overbought/oversold levels
    
    Outputs (all shift(1) for lag safety):
      - volume_weighted_rsi_bull: True when weighted RSI crosses above oversold (30)
      - volume_weighted_rsi_bear: True when weighted RSI crosses below overbought (70)
    
    Args:
        df: OHLCV DataFrame with 'Close' and 'Volume' columns
        config: Full config dict
        
    Returns:
        df copy with volume_weighted_rsi_* columns added
    """
    # Get parameters with scalping-friendly defaults
    tv_config = config.get('tv_indicators', {}).get('volume_weighted_rsi', {})
    rsi_period = tv_config.get('rsi_period', 8)          # 3-14 for scalping
    volume_lookback = tv_config.get('volume_lookback', 5)  # 3-14 for scalping
    overbought = tv_config.get('overbought', 70)
    oversold = tv_config.get('oversold', 30)
    
    # Ensure scalping constraints
    rsi_period = min(max(rsi_period, 3), 14)
    volume_lookback = min(max(volume_lookback, 3), 14)
    
    out = df.copy()
    close = out["Close"].astype(float).values
    volume = out["Volume"].astype(float).values
    
    # 1. Calculate standard RSI
    rsi = talib.RSI(close, timeperiod=rsi_period)
    
    # 2. Calculate volume weight factor
    # Volume SMA for normalization
    volume_sma = talib.SMA(volume, timeperiod=volume_lookback)
    
    # Avoid division by zero
    volume_sma = np.where(volume_sma == 0, 1, volume_sma)
    
    # Volume weight: current volume relative to recent average
    volume_weight = volume / volume_sma
    
    # 3. Calculate weighted RSI
    # Cap extreme weights to avoid distortion
    volume_weight = np.clip(volume_weight, 0.5, 2.0)
    weighted_rsi = rsi * volume_weight
    
    # 4. Generate signals
    # Convert to pandas Series for shift operations
    weighted_rsi_series = pd.Series(weighted_rsi, index=out.index)
    
    # Bullish: weighted RSI crosses above oversold level with volume spike
    rsi_bull_raw = (weighted_rsi_series > oversold) & (weighted_rsi_series.shift(1) <= oversold)
    
    # Bearish: weighted RSI crosses below overbought level with volume spike
    rsi_bear_raw = (weighted_rsi_series < overbought) & (weighted_rsi_series.shift(1) >= overbought)
    
    # 5. Apply shift(1) for lag safety
    out["volume_weighted_rsi"] = weighted_rsi_series.shift(1)
    out["volume_weighted_rsi_bull"] = rsi_bull_raw.shift(1).fillna(False).astype(bool)
    out["volume_weighted_rsi_bear"] = rsi_bear_raw.shift(1).fillna(False).astype(bool)
    out["volume_weighted_rsi_raw"] = pd.Series(rsi, index=out.index).shift(1)
    out["volume_weighted_rsi_weight"] = pd.Series(volume_weight, index=out.index).shift(1)
    
    return out