"""
features/tv_indicators/vortex_indicator.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T22:56:29
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any

def add_vortex_indicator_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Vortex Indicator features for scalping (short periods 3-14 bars).

    Args:
        df: OHLCV DataFrame
        config: Full config dict. Reads config["tv_indicators"]["vortex_indicator"]["period"].

    Returns:
        df copy with vortex_indicator columns added.
    """
    # Get config with scalping defaults
    vortex_cfg = config.get("tv_indicators", {}).get("vortex_indicator", {})
    period = vortex_cfg.get("period", 7)  # Default to 7 for 5M scalping
    
    # Ensure period is within scalping range
    period = max(3, min(period, 14))
    
    out = df.copy()
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    close = out["Close"].astype(float).values
    
    # Calculate True Range (TR)
    tr = np.maximum(
        np.maximum(high - low, np.abs(high - np.roll(close, 1))),
        np.abs(low - np.roll(close, 1))
    )
    tr[0] = high[0] - low[0]  # First TR is High - Low
    
    # Calculate VM+ and VM-
    vm_plus = np.abs(high - np.roll(low, 1))
    vm_minus = np.abs(low - np.roll(high, 1))
    vm_plus[0] = 0
    vm_minus[0] = 0
    
    # Calculate rolling sums
    tr_sum = pd.Series(tr).rolling(window=period).sum()
    vm_plus_sum = pd.Series(vm_plus).rolling(window=period).sum()
    vm_minus_sum = pd.Series(vm_minus).rolling(window=period).sum()
    
    # Calculate Vortex Indicator values
    vi_plus = vm_plus_sum / tr_sum
    vi_minus = vm_minus_sum / tr_sum
    
    # Shift for lag safety
    vi_plus_shifted = vi_plus.shift(1)
    vi_minus_shifted = vi_minus.shift(1)
    
    # Create boolean columns
    out["vortex_indicator_bull"] = vi_plus_shifted > vi_minus_shifted
    out["vortex_indicator_bear"] = vi_minus_shifted > vi_plus_shifted
    
    return out