"""
features/tv_indicators/vwap_stdev_band_breakout.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T14:40:23
"""
import numpy as np
import pandas as pd
import talib

def add_vwap_stdev_band_breakout_features(df, config):
    df = df.copy()
    
    vwap_period = config.get('vwap_period', 20)
    stdev_period = config.get('stdev_period', 20)
    stdev_multiplier = config.get('stdev_multiplier', 2.0)
    
    typical_price = (df['High'] + df['Low'] + df['Close']) / 3
    
    cumulative_volume = df['Volume'].cumsum()
    cumulative_typical_price_volume = (typical_price * df['Volume']).cumsum()
    vwap = cumulative_typical_price_volume / cumulative_volume
    
    stdev = typical_price.rolling(window=stdev_period).std()
    
    upper_band = vwap + (stdev * stdev_multiplier)
    lower_band = vwap - (stdev * stdev_multiplier)
    
    bull_breakout = (df['Close'] > upper_band) & (df['Close'].shift(1) <= upper_band.shift(1))
    bear_breakout = (df['Close'] < lower_band) & (df['Close'].shift(1) >= lower_band.shift(1))
    
    df['vwap_stdev_band_breakout_bull'] = bull_breakout.shift(1)
    df['vwap_stdev_band_breakout_bear'] = bear_breakout.shift(1)
    
    return df