"""
features/tv_indicators/williams_fractal_energy.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T14:33:37
"""
import numpy as np
import pandas as pd
import talib
from typing import Dict, Any

def add_williams_fractal_energy_features(df: pd.DataFrame, config: Dict[str, Any]) -> pd.DataFrame:
    """
    Compute Williams Fractal Energy oscillator for scalping (5M timeframe).
    
    Calculates volatility energy via fractal dimension rate of change.
    Bullish when FE > 0 (positive momentum/oversold bounce).
    Bearish when FE < 0 (negative momentum/overbought reversal).
    All outputs shift(1) for lag safety.
    """
    tv_cfg = config.get('tv_indicators', {}).get('williams_fractal_energy', {})
    period = tv_cfg.get('period', 10)
    
    # Scalping constraint: limit to 3-14 bars
    period = min(max(period, 3), 14)
    
    out = df.copy()
    high = out["High"].astype(float).values
    low = out["Low"].astype(float).values
    close = out["Close"].astype(float).values
    
    # Calculate price range components
    hl_range = high - low
    price_range = np.abs(close - np.roll(close, 1))
    price_range[0] = 0
    
    # Rolling sums for fractal dimension calculation
    def rolling_sum(arr, window):
        result = np.full_like(arr, np.nan)
        for i in range(window - 1, len(arr)):
            result[i] = np.sum(arr[i - window + 1:i + 1])
        return result
    
    sum_hl = rolling_sum(hl_range, period)
    sum_price = rolling_sum(price_range, period)
    
    # Avoid division by zero
    with np.errstate(divide='ignore', invalid='ignore'):
        ratio = np.where(sum_hl != 0, sum_price / sum_hl, 1.0)
        fractal_dim = 1 + np.log(period) / np.log(period * ratio)
        fractal_dim = np.nan_to_num(fractal_dim, nan=1.0, posinf=1.0, neginf=1.0)
    
    # Fractal Energy as rate of change
    fe = np.zeros_like(fractal_dim)
    fe[period:] = fractal_dim[period:] - fractal_dim[:-(period)]
    
    # Signal generation
    williams_fractal_energy_bull_raw = fe > 0
    williams_fractal_energy_bear_raw = fe < 0
    
    # Shift(1) for lag safety
    out["williams_fractal_energy_bull"] = pd.Series(williams_fractal_energy_bull_raw, index=out.index).shift(1)
    out["williams_fractal_energy_bear"] = pd.Series(williams_fractal_energy_bear_raw, index=out.index).shift(1)
    
    return out