"""
features/tv_indicators/williams_percent_r.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T15:19:07
"""
import numpy as np
import pandas as pd
import talib as ta

def add_williams_percent_r_features(df, config):
    out = df.copy()
    period = config.get('period', 14)
    oversold = config.get('oversold', -80)
    overbought = config.get('overbought', -20)
    neutral = config.get('neutral', -50)
    
    required_cols = ['high', 'low', 'close']
    if not all(col in out.columns for col in required_cols):
        out['williams_percent_r_bull'] = False
        out['williams_percent_r_bear'] = False
        return out
    
    high = out['high']
    low = out['low']
    close = out['close']
    
    willr = ta.WILLR(high, low, close, timeperiod=period)
    willr_series = pd.Series(willr, index=out.index)
    willr_momentum_series = willr_series.diff()
    
    cross_above_oversold = (willr_series > oversold) & (willr_series.shift(1) <= oversold)
    above_neutral_positive = (willr_series > neutral) & (willr_momentum_series > 0)
    bull_condition = cross_above_oversold | above_neutral_positive
    
    cross_below_overbought = (willr_series < overbought) & (willr_series.shift(1) >= overbought)
    below_neutral_negative = (willr_series < neutral) & (willr_momentum_series < 0)
    bear_condition = cross_below_overbought | below_neutral_negative
    
    out['williams_percent_r_bull'] = bull_condition.shift(1).fillna(False).astype(bool)
    out['williams_percent_r_bear'] = bear_condition.shift(1).fillna(False).astype(bool)
    
    return out