"""
features/tv_indicators/zero_lag_ema_ribbon_crossover.py - Auto-generated scalping indicator module.
Generated by scalp_research_loop on 2026-03-22T15:35:11
"""
import numpy as np
import pandas as pd
import talib

def add_zero_lag_ema_ribbon_crossover_features(df, config):
    out = df.copy()
    
    def zlema(series, period):
        if period < 2:
            return series
        lag = (period - 1) // 2
        return talib.EMA(2 * series - series.shift(lag), timeperiod=period)
    
    close = out["Close"].values
    fast_period = config.get("fast_period", 10)
    medium_period = config.get("medium_period", 20)
    slow_period = config.get("slow_period", 30)
    
    fast_zlema = zlema(out["Close"], fast_period)
    medium_zlema = zlema(out["Close"], medium_period)
    slow_zlema = zlema(out["Close"], slow_period)
    
    fast_zlema_series = pd.Series(fast_zlema, index=out.index)
    medium_zlema_series = pd.Series(medium_zlema, index=out.index)
    slow_zlema_series = pd.Series(slow_zlema, index=out.index)
    close_series = out["Close"]
    
    bull_condition = (fast_zlema_series > medium_zlema_series) & (medium_zlema_series > slow_zlema_series) & (close_series > fast_zlema_series)
    bear_condition = (fast_zlema_series < medium_zlema_series) & (medium_zlema_series < slow_zlema_series) & (close_series < fast_zlema_series)
    
    out["zero_lag_ema_ribbon_crossover_bull"] = bull_condition.shift(1).astype(bool)
    out["zero_lag_ema_ribbon_crossover_bear"] = bear_condition.shift(1).astype(bool)
    
    return out